'use strict';
const IMPLEMENTATION_VERSION='0.16-shadow';
const CORE_INTERVAL_MS=1200;
const BACKOFF=Object.freeze([0,2000,3500,6000,10000,15000]);
const HISTORY_CACHE_MAX_KEYS=12;
const HISTORY_CACHE_MAX_ROWS=40;
function createState(){return{running:false,stopped:false,inflight:null,pending:false,dueAt:0,generation:0,acceptedGeneration:0,failures:0,nextAllowedAt:0,overlapSkips:0,scheduledRuns:0,requestCoalesces:0,credentialEpoch:0,credentialRotations:0,staleEndpointRetries:0,lastTickMs:0,maxTickMs:0,lastError:'',requests:new Map(),historyCache:new Map(),historyInteractiveInflight:0,historyRequests:0,historyCacheHits:0,historyCacheMisses:0,historyCoalesces:0,historyInteractive:0,historyBackground:0,historyProbe:0,historyLastMs:0,historyMaxMs:0,historyBackgroundWaits:0,historyLastKey:'',historyLastRows:0,historyLastScanned:0}}
function backoffMs(failures){return BACKOFF[Math.min(BACKOFF.length-1,Math.max(0,Number(failures)||0))]||0}
function credentialSignature(creds){if(!creds||typeof creds!=='object')return'';const keys=['port','password','token','protocol','address','host'];const picked=keys.map(k=>`${k}:${String(creds[k]??'')}`).join('|');if(picked.replace(/[^:|]/g,''))return picked;try{return JSON.stringify(creds)}catch{return String(creds)}}
function historyIdentity(opts){const target=opts?.target&&typeof opts.target==='object'?opts.target:{};if(target.current===true)return'current';const bits=['puuid','summonerId','accountId','riotId','gameName','tagLine','name'].map(k=>String(target[k]??'').trim().toLowerCase()).filter(Boolean);return bits.length?bits.join('#'):'current'}
function historyTargetKey(opts){return`${opts?.queueMode==='mayhem'?'mayhem':'standard'}|${historyIdentity(opts)}`}
function historyGameKey(g){for(const r of [g,g?.game,g?.match,g?.data,g?.raw,g?.info]){const v=r?.gameId??r?.id??r?.metadata?.matchId??r?.matchId;if(v!==undefined&&v!==null&&String(v))return String(v)}return''}
function historyGameTime(g){for(const r of [g,g?.game,g?.match,g?.data,g?.raw,g?.info])for(const v of [r?.gameEndTimestamp,r?.gameEnd,r?.timestamp,r?.ts,r?.createdAt,r?.gameCreation,r?.gameCreationDate,r?.gameStartTimestamp]){const n=Number(v);if(Number.isFinite(n)&&n>0)return n}return 0}
function mergeHistoryPayload(previous,next){if(!previous)return next;if(!next)return previous;const rows=[],seen=new Set();for(const g of [...(Array.isArray(next.matches)?next.matches:[]),...(Array.isArray(previous.matches)?previous.matches:[])]){const key=historyGameKey(g)||`fallback:${historyGameTime(g)}:${rows.length}`;if(seen.has(key))continue;seen.add(key);rows.push(g)}rows.sort((a,b)=>historyGameTime(b)-historyGameTime(a));const out={...previous,...next,matches:rows.slice(0,HISTORY_CACHE_MAX_ROWS)};out.scanned=Math.max(Number(previous.scanned)||0,Number(next.scanned)||0);out.fullTeamCount=Math.max(Number(previous.fullTeamCount)||0,Number(next.fullTeamCount)||0);return out}
function decorateHistoryResult(out,meta){return!out||typeof out!=='object'?out:{...out,_historyLatency:{version:IMPLEMENTATION_VERSION,...meta}}}
function createCoordinator(opts={}){
  const state=createState(),now=typeof opts.now==='function'?opts.now:()=>Date.now();
  function singleFlight(key,fn){const existing=state.requests.get(key);if(existing){state.requestCoalesces++;return existing}let p;p=Promise.resolve().then(fn).finally(()=>{if(state.requests.get(key)===p)state.requests.delete(key)});state.requests.set(key,p);return p}
  function cacheHistory(key,payload){if(!payload||payload.connected===false||!Array.isArray(payload.matches))return;const prev=state.historyCache.get(key),merged=mergeHistoryPayload(prev?.payload,payload);state.historyCache.delete(key);state.historyCache.set(key,{at:now(),payload:merged});while(state.historyCache.size>HISTORY_CACHE_MAX_KEYS){const first=state.historyCache.keys().next().value;state.historyCache.delete(first)}}
  function cachedHistory(key){const e=state.historyCache.get(key);return e?{at:e.at,payload:e.payload}:null}
  function reset(){state.running=false;state.stopped=true;state.pending=false;state.dueAt=0;state.requests.clear();state.historyCache.clear();state.historyInteractiveInflight=0}
  function stats(){return{version:IMPLEMENTATION_VERSION,running:state.running,stopped:state.stopped,busy:!!state.inflight,generation:state.generation,acceptedGeneration:state.acceptedGeneration,failures:state.failures,nextAllowedAt:state.nextAllowedAt,overlapSkips:state.overlapSkips,scheduledRuns:state.scheduledRuns,requestCoalesces:state.requestCoalesces,credentialEpoch:state.credentialEpoch,credentialRotations:state.credentialRotations,staleEndpointRetries:state.staleEndpointRetries,lastTickMs:state.lastTickMs,maxTickMs:state.maxTickMs,lastError:state.lastError,history:{requests:state.historyRequests,cacheHits:state.historyCacheHits,cacheMisses:state.historyCacheMisses,coalesces:state.historyCoalesces,interactive:state.historyInteractive,background:state.historyBackground,probe:state.historyProbe,interactiveInflight:state.historyInteractiveInflight,backgroundWaits:state.historyBackgroundWaits,lastMs:state.historyLastMs,maxMs:state.historyMaxMs,lastKey:state.historyLastKey,lastRows:state.historyLastRows,lastScanned:state.historyLastScanned,cacheKeys:state.historyCache.size}}}
  return{state,singleFlight,cacheHistory,cachedHistory,reset,stats};
}
module.exports={IMPLEMENTATION_VERSION,CORE_INTERVAL_MS,BACKOFF,HISTORY_CACHE_MAX_KEYS,HISTORY_CACHE_MAX_ROWS,createState,createCoordinator,backoffMs,credentialSignature,historyIdentity,historyTargetKey,historyGameKey,historyGameTime,mergeHistoryPayload,decorateHistoryResult,production_active:false,score_logic_changed:false,random_scoring_changed:false};
