'use strict';
const IMPLEMENTATION_VERSION='0.16-shadow';
function createDnaEngine({normalizeName=(v=>String(v||'').trim()),candidateMeta=(()=>null),pickReferenceModel}={}){
  if(typeof pickReferenceModel!=='function')throw new Error('pickReferenceModel function required');
  function candidateRoleSignals(row,name,desc){
    const texts=[String(desc||''),String(row?.textContent||'')],names=[normalizeName(name)];
    row?.querySelectorAll?.('.comboIconLine [data-champion-name],.comboIconLine [data-name],.comboIconLine img').forEach(el=>{const v=normalizeName(el?.dataset?.championName||el?.dataset?.name||el?.getAttribute?.('alt')||el?.getAttribute?.('title')||'');if(v&&v.length<=24&&!names.includes(v))names.push(v)});
    const metas=[];names.forEach(n=>{try{const m=candidateMeta(n);if(m)metas.push(m)}catch{}});metas.forEach(m=>{texts.push(String(m?.role||''),String(m?.class||''),String(m?.position||''),String(m?.damageType||m?.damage_type||''));if(Array.isArray(m?.roles))texts.push(m.roles.join(' '));if(Array.isArray(m?.tags))texts.push(m.tags.join(' '))});
    const t=texts.join(' ').toLowerCase(),s={engage:0,poke:0,front:0,sustain:0,cc:0},raise=(k,v)=>{s[k]=Math.max(s[k],v)};
    if(/이니시|진입|교전|engage|initiat|dive|돌진/.test(t))raise('engage',1);if(/포킹|poke|artillery|장거리 견제|사거리/.test(t))raise('poke',1);if(/프론트|앞라인|탱커|frontline|\btank\b|vanguard|warden/.test(t))raise('front',1);if(/지속 전투|지속딜|sustain|회복|힐|보호|쉴드|enchanter|유지력/.test(t))raise('sustain',1);if(/군중|제어|\bcc\b|stun|root|knock|silence|slow|속박|기절|에어본/.test(t))raise('cc',1);
    if(/\btank\b|탱커|vanguard|warden/.test(t)){raise('engage',.82);raise('front',1);raise('cc',.78);raise('sustain',.55)}if(/fighter|bruiser|juggernaut|브루저|전사/.test(t)){raise('engage',.5);raise('front',.72);raise('sustain',.7)}if(/assassin|암살/.test(t))raise('engage',.72);if(/marksman|원딜|adc/.test(t))raise('sustain',.74);if(/support|서포터|enchanter|강화형/.test(t)){raise('sustain',.95);raise('cc',.58)}if(/mage|메이지/.test(t)){raise('poke',.46);raise('cc',.34)}return s;
  }
  function mergeDnaMetric(base,signal){const b=base||{pct:0,state:'확인',missing:false},v=Math.max(0,Math.min(1,Number(signal)||0)),bp=Math.max(0,Math.min(100,Number(b.pct)||0));if(b.missing){if(v>=.74)return{pct:Math.max(78,Math.min(94,Math.round(70+v*22))),state:'보완',missing:false,preview:true};if(v>=.45)return{pct:Math.max(52,Math.min(72,Math.round(42+v*35))),state:'부분 보완',missing:true,preview:true};return{pct:bp||24,state:'부족',missing:true,preview:false}}if(v>=.74)return{pct:Math.min(96,Math.max(bp,Math.round(80+v*16))),state:'강화',missing:false,preview:true};if(v>=.45)return{pct:Math.min(90,Math.max(bp,Math.round(72+v*18))),state:'확보+',missing:false,preview:true};return{pct:bp||78,state:b.state||'확보',missing:false,preview:false}}
  function shortageSignal(text,signals,profile){const t=String(text||'').toLowerCase();if(/이니시|진입|교전|engage/.test(t))return signals.engage;if(/포킹|poke/.test(t))return signals.poke;if(/프론트|앞라인|탱커|frontline/.test(t))return signals.front;if(/지속|유지|보호|회복|sustain/.test(t))return signals.sustain;if(/군중|제어|\bcc\b/.test(t))return signals.cc;if(/\bad\b|물리/.test(t))return Number(profile?.adPct)>=55?1:0;if(/\bap\b|마법/.test(t))return Number(profile?.apPct)>=35?1:0;return 0}
  function candidateDnaPreview(row,name,desc,profile){const m=pickReferenceModel(),signals=candidateRoleSignals(row,name,desc),dna={engage:mergeDnaMetric(m.dna.engage,signals.engage),poke:mergeDnaMetric(m.dna.poke,signals.poke),front:mergeDnaMetric(m.dna.front,signals.front),sustain:mergeDnaMetric(m.dna.sustain,signals.sustain),cc:mergeDnaMetric(m.dna.cc,signals.cc)},shortages=(m.shortages||[]).filter(x=>shortageSignal(x,signals,profile)<.74);if(!shortages.length){const missing=[];if(dna.engage.missing)missing.push('이니시');if(dna.poke.missing)missing.push('포킹');if(dna.front.missing)missing.push('프론트라인');if(dna.sustain.missing)missing.push('지속 전투');if(dna.cc.missing)missing.push('군중 제어');shortages.push(...missing.slice(0,6))}return{m,signals,dna,shortages,profile}}
  return{candidateRoleSignals,mergeDnaMetric,shortageSignal,candidateDnaPreview};
}
module.exports={IMPLEMENTATION_VERSION,createDnaEngine,production_active:false,score_logic_changed:false,random_scoring_changed:false};
