'use strict';
const fs=require('fs');
const path=require('path');
const SAFETY_BASELINE_LINEAGE_V015107=Object.freeze({via:'main-v015106.js',root:'main-v01579.js',reason:'data-random-view-boundary-and-random-pick-layout-repair'});
void SAFETY_BASELINE_LINEAGE_V015107;
const basePath=path.join(__dirname,'main-v015106.js');
let src=fs.readFileSync(basePath,'utf8');
const marker='0.15.106';
const hits=src.split(marker).length-1;
if(hits<3)throw new Error('v0.15.107 successor contract mismatch: v0.15.106 markers='+hits);
const stabilityAnchor='runtime-source-stability-v015106';
if(src.split(stabilityAnchor).length-1<1)throw new Error('v0.15.107 source-stability anchor mismatch');
src=src.replaceAll('0.15.106','0.15.107').replaceAll(stabilityAnchor,'runtime-source-stability-v015107');
module._compile(src,__filename);
