'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {MemoryRatingStore,JsonRatingStore,UniversalRatingService,normalizeMatch,fingerprint,createEstimator}=require('../src/rating/universal');
function raw(id,t,target='A',win=true){const a=[target,`${id}a1`,`${id}a2`,`${id}a3`,`${id}a4`],b=[`${id}b1`,`${id}b2`,`${id}b3`,`${id}b4`,`${id}b5`];return{gameId:id,gameEndTimestamp:t,gameVersion:'26.18.1',queueId:450,participants:[...a.map((puuid,i)=>({puuid,teamId:100,win,kills:i+1,deaths:2,assists:8,totalDamageDealtToChampions:12000+i})),...b.map((puuid,i)=>({puuid,teamId:200,win:!win,kills:i,deaths:4,assists:4,totalDamageDealtToChampions:9000+i}))]}}
function fakeConnector(rowsByPlayer){const rawById=new Map(),calls={resolve:0,ids:0,detail:0};for(const rows of Object.values(rowsByPlayer))for(const x of rows)rawById.set(String(x.gameId),x);return{calls,async resolvePlayer(query){calls.resolve++;const puuid=typeof query==='string'?query:String(query?.puuid||query?.gameName||'');return{puuid,gameName:`name-${puuid}`}},async fetchMatchIds(puuid){calls.ids++;return(rowsByPlayer[puuid]||[]).map(x=>String(x.gameId))},async fetchMatch(id){calls.detail++;return rawById.get(String(id))}}}
function fakeEstimator(modelVersion='test-model-v1'){return{modelVersion,async estimate({puuid,matches}){const games=matches.filter(m=>m.teamA.includes(puuid)||m.teamB.includes(puuid)).length;return{status:games?'ESTIMATED_SHADOW':'INSUFFICIENT_DATA',rating:games?1500+games:null,uncertainty:games?100:null,games,modelName:'fixture',modelStatus:'SHADOW'}}}}
test('canonical fingerprint is independent from app version metadata',()=>{const a=normalizeMatch({...raw('m1',1000),appVersion:'0.16.0'}),b=normalizeMatch({...raw('m1',1000),appVersion:'9.99.0'});assert.deepEqual(a,b);assert.equal(fingerprint([a],'model-v1'),fingerprint([b],'model-v1'))});
test('any searched player can be rated without current-user dependency',async()=>{const connector=fakeConnector({stranger:[raw('s1',1000,'stranger'),raw('s2',2000,'stranger',false)]});const service=new UniversalRatingService({connector,store:new MemoryRatingStore(),estimator:fakeEstimator()});const r=await service.lookup('stranger');assert.equal(r.puuid,'stranger');assert.equal(r.rating,1502);assert.equal(r.targetMatches,2);assert.equal(r.productionActive,false)});
test('incremental lookup deduplicates matches and avoids refetching known details',async()=>{const rows=[raw('a1',1000,'A'),raw('a2',2000,'A')],connector=fakeConnector({A:rows}),store=new MemoryRatingStore(),service=new UniversalRatingService({connector,store,estimator:fakeEstimator()});const first=await service.lookup('A'),detailAfterFirst=connector.calls.detail,second=await service.lookup('A');assert.equal(first.newMatches,2);assert.equal(detailAfterFirst,2);assert.equal(second.cacheHit,true);assert.equal(connector.calls.detail,2);assert.equal(store.getAllMatches().length,2)});
test('model version is an explicit rating key and forces separate records',async()=>{const rows=[raw('v1',1000,'A')],connector=fakeConnector({A:rows}),store=new MemoryRatingStore();await new UniversalRatingService({connector,store,estimator:fakeEstimator('model-v1')}).lookup('A');await new UniversalRatingService({connector,store,estimator:fakeEstimator('model-v2')}).lookup('A');assert.ok(store.getRating('model-v1','A'));assert.ok(store.getRating('model-v2','A'));assert.notEqual(store.getRating('model-v1','A').evidenceFingerprint,store.getRating('model-v2','A').evidenceFingerprint)});
test('persistent store survives app restarts without install-version coupling',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aram-rating-')),file=path.join(dir,'universal-rating.json');const m=normalizeMatch(raw('p1',1000,'A'));let s=new JsonRatingStore(file);s.putMatches([m]);s.putPlayer({puuid:'A'});s.putRating({modelVersion:'m1',puuid:'A',rating:1550});s=new JsonRatingStore(file);assert.equal(s.getAllMatches().length,1);assert.equal(s.getRating('m1','A').rating,1550);fs.rmSync(dir,{recursive:true,force:true})});
test('research candidate estimator remains shadow-only',async()=>{const rows=[];for(let i=0;i<12;i++)rows.push(normalizeMatch(raw(`e${i}`,1000+i,'A',i%2===0)));const est=createEstimator('research-v032-elo-shadow'),r=await est.estimate({puuid:'A',matches:rows});assert.equal(est.productionActive,false);assert.equal(r.modelStatus,'SHADOW');assert.equal(r.games,12);assert.ok(Number.isFinite(r.rating))});