'use strict';
const crypto=require('crypto');
const {invariant}=require('./contracts');
const roots=g=>[g,g?.game,g?.match,g?.data,g?.raw,g?.info].filter(Boolean);
function pick(g,keys){for(const r of roots(g))for(const k of keys){const v=r?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null}
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const bool=v=>typeof v==='boolean'?v:(v===1||v==='true'?true:v===0||v==='false'?false:null);
const idOf=p=>String(p?.puuid||p?.player?.puuid||'').trim();
function participants(g){for(const r of roots(g)){if(Array.isArray(r?.participants)&&r.participants.length)return r.participants;if(Array.isArray(r?.participantIdentities)&&Array.isArray(r?.participants))return r.participants;const a=Array.isArray(r?.team)?r.team:[],b=Array.isArray(r?.enemy)?r.enemy:[];if(a.length||b.length)return [...a,...b]}return[]}
function timestampOf(g){const v=pick(g,['gameEndTimestamp','gameEnd','timestamp','ts','createdAt','gameCreation','gameCreationDate','gameStartTimestamp']);if(typeof v==='string'&&!/^\d+(\.\d+)?$/.test(v)){const t=Date.parse(v);return Number.isFinite(t)?t:0}const n=Number(v);return Number.isFinite(n)?n:0}
function patchOf(g){const raw=String(pick(g,['gameVersion','patch','version'])||'UNKNOWN');const m=raw.match(/^(\d+)\.(\d+)/);return m?`${m[1]}.${m[2]}`:raw}
function statsOf(p){const s=p?.stats||p||{};const out={};for(const [k,aliases] of Object.entries({kills:['kills'],deaths:['deaths'],assists:['assists'],damage:['totalDamageDealtToChampions','damage','championDamage'],taken:['totalDamageTaken','taken'],gold:['goldEarned','gold'],cc:['timeCCingOthers','totalTimeCrowdControlDealt','cc'],healing:['totalHeal','healing'],shielding:['totalDamageShieldedOnTeammates','shielding'],minions:['totalMinionsKilled','minionsKilled','cs']})){for(const a of aliases){const v=num(s?.[a]);if(v!==null){out[k]=v;break}}}return out}
function normalizeParticipant(p,index){const puuid=idOf(p);if(!puuid)return null;const teamId=num(p?.teamId??p?.team?.id);const win=bool(p?.win??p?.stats?.win);return{puuid,teamId:teamId??(index<5?100:200),win,championId:num(p?.championId??p?.champion?.id),...statsOf(p)}}
function normalizeMatch(g,{queueId=450}={}){const q=num(pick(g,['queueId','queue_id']));if(q!==null&&queueId!==null&&q!==Number(queueId))return null;const matchId=String(pick(g,['gameId','id','matchId','match_id'])||'').trim(),timestamp=timestampOf(g);if(!matchId||!timestamp)return null;const ps=participants(g).map(normalizeParticipant).filter(Boolean);if(ps.length!==10||new Set(ps.map(x=>x.puuid)).size!==10)return null;let a=ps.filter(x=>x.teamId===100),b=ps.filter(x=>x.teamId===200);if(a.length!==5||b.length!==5){a=ps.slice(0,5).map(x=>({...x,teamId:100}));b=ps.slice(5).map(x=>({...x,teamId:200}))}if(a.length!==5||b.length!==5)return null;let teamAWin=a.map(x=>x.win).find(x=>typeof x==='boolean');if(typeof teamAWin!=='boolean'){const teamBWin=b.map(x=>x.win).find(x=>typeof x==='boolean');if(typeof teamBWin==='boolean')teamAWin=!teamBWin}if(typeof teamAWin!=='boolean')return null;return{schemaVersion:1,matchId,timestamp,patch:patchOf(g),queueId:q??Number(queueId),teamA:a.map(x=>x.puuid).sort(),teamB:b.map(x=>x.puuid).sort(),teamAWin,participants:[...a,...b].sort((x,y)=>x.puuid.localeCompare(y.puuid))}}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value}
function fingerprint(matches,modelVersion){invariant(modelVersion,'modelVersion required');const evidence=(Array.isArray(matches)?matches:[]).map(m=>({matchId:m.matchId,timestamp:m.timestamp,patch:m.patch,teamA:m.teamA,teamB:m.teamB,teamAWin:m.teamAWin,participants:m.participants})).sort((a,b)=>a.timestamp-b.timestamp||a.matchId.localeCompare(b.matchId));return crypto.createHash('sha256').update(JSON.stringify(stable({modelVersion,evidence}))).digest('hex')}
module.exports={num,bool,idOf,participants,timestampOf,patchOf,statsOf,normalizeParticipant,normalizeMatch,stable,fingerprint,production_active:false};