'use strict';
const storage=require('./storage');
const engine=require('./rating-engine');
const ui=require('./ui-core');
const IMPLEMENTATION_VERSION='0.16-shadow';
const IDS=Object.freeze({style:'researchCanonicalStyleV016',host:'researchCanonicalHostV016'});
const STYLE=`
[data-ui-role="research-card"]{margin:16px 0}.arui-card{padding:17px;border:1px solid rgba(91,132,190,.28);border-radius:16px;background:linear-gradient(145deg,rgba(12,24,43,.98),rgba(18,31,53,.96));box-shadow:0 16px 40px rgba(0,0,0,.18);color:#e8eff9}.arui-head{display:flex;justify-content:space-between;gap:12px}.arui-head h3{display:inline-block;margin:0 0 0 8px;font-size:15px}.arui-badge{display:inline-flex;border:1px solid rgba(75,190,255,.5);border-radius:999px;padding:3px 7px;color:#8ed8ff;font-size:9px;font-weight:800}.arui-refresh{border:1px solid rgba(122,151,190,.28);border-radius:9px;background:rgba(255,255,255,.035);color:#a9bad0;width:30px;height:30px;cursor:pointer}.arui-summary,.arui-models{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:10px}.arui-summary>div,.arui-model{padding:10px;border:1px solid rgba(113,142,180,.15);border-radius:11px;background:rgba(255,255,255,.025)}.arui-model strong{display:block;margin-top:8px;font-size:21px}.arui-player-meta{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:9px}.arui-player-meta>div{padding:9px;border:1px solid rgba(113,142,180,.1);border-radius:10px}.arui-dataset-mini{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px}.arui-dataset-mini span{padding:4px 7px;border-radius:999px;background:rgba(73,96,127,.14);color:#8295ae;font-size:8px}.arui-details{margin-top:10px;border-top:1px solid rgba(104,132,169,.13);padding-top:9px}.arui-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.arui-detail-block{padding:10px;border:1px solid rgba(106,139,181,.11);border-radius:10px}.arui-detail-block table{width:100%;border-collapse:collapse;font-size:9px}.arui-foot,.arui-disclaimer{margin-top:9px;color:#60738c;font-size:8px}.arui-empty{margin-top:14px;padding:20px 12px;text-align:center;border:1px dashed rgba(116,145,184,.18);border-radius:12px}@media(max-width:860px){.arui-summary,.arui-models{grid-template-columns:1fr}.arui-player-meta{grid-template-columns:1fr 1fr}.arui-detail-grid{grid-template-columns:1fr}}`;
function createResearchOwner({document,indexedDBRef=globalThis.indexedDB,getPuuid=(()=>''),hardCap=500,resolveProfileBody=null,onState=(()=>{})}={}){
  if(!document)throw new Error('document required');let disposed=false,latest=null,lastState='idle',diagnostic=null,hostListener=null;
  function ensureStyle(){let st=document.getElementById?.(IDS.style);if(st)return st;st=document.createElement?.('style');if(!st)return null;st.id=IDS.style;st.textContent=STYLE;(document.head||document.body)?.appendChild?.(st);return st}
  function profileBody(){if(typeof resolveProfileBody==='function'){const x=resolveProfileBody();if(x)return x}return document.querySelector?.('#profileCanonicalContentV016 .ppbody')||document.querySelector?.('#pp19c .ppbody')||null}
  function ensureHost(){let h=document.getElementById?.(IDS.host);if(h)return h;const body=profileBody();if(!body)return null;h=document.createElement?.('div');if(!h)return null;h.id=IDS.host;h.setAttribute?.('data-ui-role','research-card');hostListener=e=>{if(e?.target?.closest?.('[data-arui-action="refresh"]')){e.preventDefault?.();e.stopPropagation?.();void refresh()}};h.addEventListener?.('click',hostListener);const hero=body.querySelector?.('.pphero');if(hero?.insertAdjacentElement)hero.insertAdjacentElement('afterend',h);else body.prepend?.(h)||body.appendChild?.(h);return h}
  function render(){if(disposed)return false;ensureStyle();const h=ensureHost();if(!h)return false;let vm;if(lastState==='available'&&latest)vm=ui.buildViewModel(latest,getPuuid(),{hardCap});else if(lastState==='checkpoint_missing'||lastState==='dataset_empty')vm={kind:'unavailable',message:lastState==='checkpoint_missing'?'Research checkpoint missing':'Research dataset empty'};else if(lastState==='database_unavailable')vm={kind:'unavailable',message:'Research data unavailable'};else vm={kind:'unavailable',message:'Research data loading'};h.innerHTML=ui.renderCard(vm);h.dataset=h.dataset||{};h.dataset.researchState=lastState;return true}
  async function load({forceBuild=false}={}){if(disposed)return{state:'disposed',run:null,diagnostic:null};const r=await storage.loadExisting({indexedDBRef,engine,forceBuild});latest=r.run||null;lastState=r.state;diagnostic=r.diagnostic||null;render();onState({state:lastState,run:latest,diagnostic});return r}
  async function refresh(){return load({forceBuild:true})}
  function dispose(){if(disposed)return;disposed=true;const h=document.getElementById?.(IDS.host),st=document.getElementById?.(IDS.style);if(h&&hostListener)h.removeEventListener?.('click',hostListener);h?.remove?.();st?.remove?.();hostListener=null;latest=null}
  return{ensureStyle,ensureHost,render,load,refresh,dispose,get latestRun(){return latest},get state(){return lastState},get diagnostic(){return diagnostic},get disposed(){return disposed}};
}
module.exports={IMPLEMENTATION_VERSION,IDS,STYLE,createResearchOwner,engine,ui,production_active:false,automatic_collection:false,b2_manual_only:true,destructive_migration:false,network_collection_default:false,owner_status:'shadow',score_logic_changed:false,random_scoring_changed:false};
