'use strict';
const fs=require('fs');
const path=require('path');
const SAFETY_BASELINE_LINEAGE_V015121=Object.freeze({via:'main-v015120.js',root:'main-v01579.js',reason:'random-practice-restore'});
void SAFETY_BASELINE_LINEAGE_V015121;
const basePath=path.join(__dirname,'main-v015120.js');
let src=fs.readFileSync(basePath,'utf8');
const oldRoute=`src=src.replace(oldRoute,"src=src.replaceAll('0.15.113','0.15.120').replaceAll(stabilityAnchor,'runtime-source-stability-v015120');");`;
const newRoute=`src=src.replace(oldRoute,"src=src.replaceAll('0.15.113','0.15.121').replaceAll(stabilityAnchor,'runtime-source-stability-v015121');");`;
if(!src.includes(oldRoute))throw new Error('v0.15.121 main successor contract mismatch: v0.15.120 route missing');
src=src.replace(oldRoute,newRoute);
module._compile(src,__filename);
