'use strict';
const IMPLEMENTATION_VERSION='0.16-shadow';
const DB_NAME='aram-rating-research-v03',STORE='kv',CHECKPOINT_KEY='checkpoint-v03',LATEST_RUN_KEY='rating-ui-latest-run-v01';
const arr=x=>Array.isArray(x)?x:[];
function checkpointStamp(cp){const xs=arr(cp?.matches),last=xs.at(-1),id=last?.gameId??last?.id??last?.matchId??'';return[cp?.seed_fingerprint||'',cp?.phase||'',cp?.status||'',cp?.sampling_version||cp?.config?.samplingVersion||'',xs.length,cp?.finished_at_v031||cp?.finished_at||'',id].join('|')}
function sourceMeta(cp){return{phase:String(cp?.phase||'UNKNOWN'),status:String(cp?.status||'unknown'),sampling_version:String(cp?.sampling_version||cp?.config?.samplingVersion||'v0.3'),source:`IndexedDB ${DB_NAME}/${CHECKPOINT_KEY}`}}
async function databaseExistsHint(idb,name){if(typeof idb?.databases!=='function')return null;try{return(await idb.databases()).some(x=>x?.name===name)}catch{return null}}
async function openExistingDatabase(idb,name=DB_NAME){
  if(!idb?.open)throw Object.assign(new Error('indexedDB_unavailable'),{stage:'indexeddb_open'});
  return new Promise((resolve,reject)=>{let created=false;const q=idb.open(name);q.onupgradeneeded=e=>{if(Number(e.oldVersion||0)===0){created=true;try{q.transaction.abort()}catch{}}};q.onsuccess=()=>resolve({db:q.result,missing:false});q.onerror=()=>created&&q.error?.name==='AbortError'?resolve({db:null,missing:true}):reject(Object.assign(q.error||new Error('indexeddb_open_failed'),{stage:'indexeddb_open'}));q.onblocked=()=>reject(Object.assign(new Error('indexeddb_open_blocked'),{stage:'indexeddb_open'}))});
}
function readKey(db,key){return new Promise((resolve,reject)=>{let tx;try{tx=db.transaction(STORE,'readonly')}catch(e){reject(Object.assign(e,{stage:'schema_check'}));return}const q=tx.objectStore(STORE).get(key);q.onsuccess=()=>resolve(q.result??null);q.onerror=()=>reject(Object.assign(q.error||new Error('indexeddb_read_failed'),{stage:`read:${key}`}))})}
function selectRun(cp,stored,opts={}){const matches=arr(cp?.matches);if(!cp)return{state:'checkpoint_missing',run:null,source:'none'};if(!matches.length)return{state:'dataset_empty',run:null,source:'checkpoint'};const stamp=(opts.checkpointStamp||checkpointStamp)(cp);if(!opts.forceBuild&&stored?.schema==='aram-rating-ui-latest-run-v01'&&stored?.source_run?.checkpoint_stamp===stamp)return{state:'available',run:stored,source:'derived_cache'};if(!opts.engine?.buildLatestRun)throw Object.assign(new Error('rating_engine_unavailable'),{stage:'rating_engine_init'});const run=opts.engine.buildLatestRun(matches,(opts.sourceMeta||sourceMeta)(cp));run.source_run={checkpoint_key:CHECKPOINT_KEY,checkpoint_stamp:stamp,checkpoint_finished_at:cp.finished_at_v031||cp.finished_at||null,checkpoint_status:cp.status||null,checkpoint_phase:cp.phase||null};return{state:'available',run,source:'checkpoint_rebuild_memory'}}
async function loadExisting(opts={}){const d={db_name:DB_NAME,indexeddb_open:false,db_version:null,object_stores:[],database_list_hint:null,checkpoint_found:false,match_count:0,player_count:0,rating_state_count:0,cache_status:'not_checked',source:'none',error_stage:'',error_name:'',error_message:''};let db=null;try{const idb=opts.indexedDBRef||globalThis.indexedDB;d.database_list_hint=await databaseExistsHint(idb,DB_NAME);const o=await openExistingDatabase(idb);if(o.missing)return{state:'checkpoint_missing',run:null,diagnostic:d};db=o.db;d.indexeddb_open=true;d.db_version=db.version;d.object_stores=Array.from(db.objectStoreNames||[]);if(!d.object_stores.includes(STORE))throw Object.assign(new Error(`object_store_missing:${STORE}`),{stage:'schema_check'});const cp=await readKey(db,CHECKPOINT_KEY);d.checkpoint_found=!!cp;d.match_count=arr(cp?.matches).length;if(!cp)return{state:'checkpoint_missing',run:null,diagnostic:d};if(!d.match_count)return{state:'dataset_empty',run:null,diagnostic:d};let cached=null;try{cached=await readKey(db,LATEST_RUN_KEY);d.cache_status=cached?'read':'missing'}catch(e){d.cache_status=`ignored_read_error:${e?.name||'Error'}`}const s=selectRun(cp,cached,opts);d.source=s.source;d.player_count=Number(s.run?.dataset?.players)||Object.keys(s.run?.players||{}).length;d.rating_state_count=Object.values(s.run?.players||{}).filter(p=>p?.models&&Object.keys(p.models).length).length;return{state:s.state,run:s.run,diagnostic:d}}catch(e){d.error_stage=e?.stage||'load';d.error_name=e?.name||'Error';d.error_message=e?.message||String(e);return{state:'database_unavailable',run:null,diagnostic:d,error:e}}finally{try{db?.close?.()}catch{}}}
module.exports={IMPLEMENTATION_VERSION,DB_NAME,STORE,CHECKPOINT_KEY,LATEST_RUN_KEY,checkpointStamp,sourceMeta,databaseExistsHint,openExistingDatabase,readKey,selectRun,loadExisting,policy_version:'0.16-shadow',read_only_boot:true,destructive_migration:false,listing_is_hint_only:true,network_collection_default:false,production_active:false,score_logic_changed:false,random_scoring_changed:false};
