'use strict';
const art=require('./art-resolver');
const IMPLEMENTATION_VERSION='0.16-shadow';
function createArtRuntime({documentRef=globalThis.document,MutationObserverClass=globalThis.MutationObserver,getCatalog=()=>globalThis.aramDesktop?.getItemCatalog?.(),registerCleanup=null}={}){
  let catalog=null,pending=null,observer=null,started=false;
  const resolver=art.createArtResolver();
  const runtime=new Map();
  const counters={scans:0,mutationBatches:0,imagesVisited:0,itemImagesResolved:0,primaryReady:0,fallbackReady:0,missing:0,sameAssetSkips:0};
  const all=(sel,root=documentRef)=>[...(root?.querySelectorAll?.(sel)||[])];
  function ensureStyle(){if(documentRef?.getElementById?.('aramItemArtCanonicalStyle'))return;const st=documentRef.createElement?.('style');if(!st)return;st.id='aramItemArtCanonicalStyle';st.textContent='img[data-aram-item-art-switching="1"]{visibility:hidden!important;transition:none!important} img[data-aram-item-art-ready="1"]{visibility:visible!important}';documentRef.head?.appendChild?.(st)}
  function setCatalog(x){catalog=x||null;resolver.setCatalog(catalog);return catalog}
  async function loadCatalog(){if(catalog?.ok)return catalog;if(pending)return pending;if(typeof getCatalog!=='function')return null;pending=Promise.resolve().then(()=>getCatalog()).then(x=>{if(x?.ok)setCatalog(x);return x||null}).catch(()=>null).finally(()=>{pending=null});return pending}
  function record(id,state,index,url){const it=catalog?.items?.[String(id)];runtime.set(String(id),{id:String(id),name:it?.name||'',state,index,url:String(url||''),at:Date.now()})}
  function markReady(img,id,index,base){img.dataset=img.dataset||{};img.dataset.itemId=String(id);img.dataset.aramItemArtReady='1';img.dataset.aramItemArtCandidate=String(index);delete img.dataset.aramItemArtSwitching;if(img.style){img.style.visibility='';img.style.display=''};if(index===0)counters.primaryReady++;else counters.fallbackReady++;record(id,index===0?'primary':'fallback',index,base)}
  function applyCandidate(img,id,index){const xs=resolver.candidates(id);if(!xs.length||index>=xs.length){if(img?.dataset)delete img.dataset.aramItemArtSwitching;if(img?.style)img.style.visibility='';counters.missing++;record(id,'missing',index,'');return}const base=xs[index];img.dataset=img.dataset||{};img.dataset.itemId=String(id);img.dataset.aramItemArtSwitching='1';delete img.dataset.aramItemArtReady;const token=`${id}:${index}:${Date.now()}:${Math.random()}`;img.dataset.aramItemArtToken=token;img.onerror=()=>{if(img.dataset.aramItemArtToken!==token)return;applyCandidate(img,id,index+1)};img.onload=()=>{if(img.dataset.aramItemArtToken!==token)return;if(!resolver.sameAsset(img.currentSrc||img.src,base)){delete img.dataset.aramItemArtSwitching;refreshImg(img);return}markReady(img,id,index,base)};record(id,'pending',index,base);img.src=base}
  function refreshImg(img){if(!img||img.tagName!=='IMG'||!catalog?.ok)return;counters.imagesVisited++;if(img.dataset?.aramItemArtSwitching==='1')return;const id=resolver.idFrom(img);if(!id)return;counters.itemImagesResolved++;const xs=resolver.candidates(id);if(!xs.length)return;const current=String(img.currentSrc||img.getAttribute?.('src')||img.src||''),own=Number(img.dataset?.aramItemArtCandidate??-1);if(img.dataset?.aramItemArtReady==='1'&&own>=0&&xs[own]&&resolver.sameAsset(current,xs[own])){counters.sameAssetSkips++;return}if(resolver.sameAsset(current,xs[0])){markReady(img,id,0,xs[0]);counters.sameAssetSkips++;return}applyCandidate(img,id,0)}
  function touch(node){if(!node||node.nodeType!==1)return;if(node.tagName==='IMG')refreshImg(node);all('img',node).forEach(refreshImg)}
  function scan(root=documentRef){if(!catalog?.ok){void loadCatalog().then(x=>{if(x?.ok)scan(root)});return}counters.scans++;if(root?.tagName==='IMG'){refreshImg(root);return}all('img',root).forEach(refreshImg)}
  function onMutations(records){counters.mutationBatches++;if(!catalog?.ok){void loadCatalog().then(x=>{if(x?.ok)scan()});return}for(const rec of records||[]){if(rec.type==='attributes'){refreshImg(rec.target);continue}for(const node of rec.addedNodes||[])touch(node)}}
  function start(){if(started)return api;started=true;ensureStyle();if(typeof MutationObserverClass==='function'&&documentRef?.documentElement){observer=new MutationObserverClass(onMutations);observer.observe(documentRef.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['src','data-item-id','alt','title']})}void loadCatalog().then(x=>{if(x?.ok)scan()});if(typeof registerCleanup==='function')registerCleanup(stop);return api}
  function stop(){started=false;try{observer?.disconnect?.()}catch{}observer=null}
  function refresh(){scan()}
  function getAuditReport(){const states=[...runtime.values()];return{version:IMPLEMENTATION_VERSION,singleOwner:true,recurringFullDocumentScan:false,observerActive:!!observer,started,catalogVersion:catalog?.version||'',runtimeItems:states.length,pending:states.filter(x=>x.state==='pending').length,primaryReady:states.filter(x=>x.state==='primary').length,fallbackReady:states.filter(x=>x.state==='fallback').length,missing:states.filter(x=>x.state==='missing').length,counters:{...counters},score_logic_changed:false}}
  const api={start,stop,refresh,refreshImg,setCatalog,loadCatalog,resolve:resolver.resolve,getAuditReport,getCatalog:()=>catalog,getObserver:()=>observer,isStarted:()=>started};
  return api;
}
module.exports={IMPLEMENTATION_VERSION,createArtRuntime,production_active:false,score_logic_changed:false,random_scoring_changed:false,item_recommendation_logic_changed:false};
