'use strict';
const contract=require('./contract');
const dna=require('./dna');
const selection=require('./selection-state');
const top5=require('./top5');
const teamScoreAdapter=require('./team-score-adapter');
const teamScore=require('./team-score');
const teamSurvival=require('./team-survival');
const candidatePreview=require('./candidate-preview');
const renderCore=require('./render-core');
const owner=require('./owner');
module.exports={contract,dna,selection,top5,teamScoreAdapter,teamScore,teamSurvival,candidatePreview,renderCore,owner,production_active:false,score_logic_changed:false,random_scoring_changed:false};
