'use strict';
const {app,BrowserWindow}=require('electron');
const fs=require('fs');
const path=require('path');
const OUT=path.resolve(__dirname,'../../audit-output/stability/windows-e2e');
function writeJson(name,obj){fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,name),JSON.stringify(obj,null,2)+'\n','utf8')}
async function waitForReady(win){for(let i=0;i<100;i++){const ok=await win.webContents.executeJavaScript('Boolean(window.__syntheticReady)').catch(()=>false);if(ok)return;await new Promise(r=>setTimeout(r,50))}throw new Error('synthetic renderer did not become ready')}
async function capture(win,scenario,file){await win.webContents.executeJavaScript(`window.aramSyntheticE2E.setScenario(${JSON.stringify(scenario)});true`);await new Promise(r=>setTimeout(r,120));const img=await win.webContents.capturePage();fs.writeFileSync(path.join(OUT,file),img.toPNG())}
async function main(){fs.rmSync(OUT,{recursive:true,force:true});fs.mkdirSync(OUT,{recursive:true});const win=new BrowserWindow({width:1440,height:960,show:false,backgroundColor:'#07141f',webPreferences:{contextIsolation:false,nodeIntegration:false,sandbox:false}});await win.loadFile(path.join(__dirname,'synthetic-ui.html'));await waitForReady(win);const report=await win.webContents.executeJavaScript('window.aramSyntheticE2E.runSyntheticE2E()');for(const [scenario,file] of [['random.pick','random-pick.png'],['random.ingame','random-ingame.png'],['data.tier','data-tier.png'],['data.patch','data-patch-notes.png'],['profile','player-profile.png'],['results','results.png']])await capture(win,scenario,file);const post=await win.webContents.executeJavaScript('window.aramDiagnosticsV1.collect({version:"0.15.135-golden",autosyncStatus:"synthetic-idle",autosyncQueueDepth:0})');report.post_capture_diagnostics=post;report.screenshot_files=['random-pick.png','random-ingame.png','data-tier.png','data-patch-notes.png','player-profile.png','results.png'];report.acceptance_scope='synthetic Electron/Chromium fixture on Windows; NOT production-installed-app acceptance';writeJson('synthetic-e2e-report.json',report);console.log('SYNTHETIC WINDOWS ELECTRON E2E: SUCCESS',report.soak);win.destroy();app.quit()}
app.whenReady().then(()=>main().catch(e=>{try{writeJson('synthetic-e2e-report.json',{status:'FAILURE',synthetic:true,error:e?.stack||String(e),acceptance_scope:'synthetic Electron/Chromium fixture on Windows; NOT production-installed-app acceptance'})}catch{};console.error(e);app.exit(1)}));
