'use strict';
const fs=require('fs');
const path=require('path');
const {app,ipcMain}=require('electron');
const {buildRendererSource}=require('./canonical-owner-bundler-v0160');
const {installUniversalRatingIpc}=require('./src/main/universal-rating-ipc');
const VERSION='0.17.1';
const STABLE_APP_ID='aram-fearless-draft';
const CLEAN_RUNTIME_LINEAGE_V0170=Object.freeze({baseline:'0.16.3',golden:'0.15.135',legacySafetyRoot:'main-v01579.js',flattened:true,runtimeSuccessorWrappers:false});
void CLEAN_RUNTIME_LINEAGE_V0170;
function installShadowDiagnostics(){const p=path.join(__dirname,'src','profile','shadow-rating-diagnostics-renderer.js');if(!fs.existsSync(p))throw new Error('v0.17 shadow diagnostics renderer missing');const source=fs.readFileSync(p,'utf8')+'\n//# sourceURL=shadow-rating-diagnostics-v0170.js';app.on('browser-window-created',(_event,win)=>{const inject=()=>{try{if(!win||win.isDestroyed?.()||win.webContents?.isDestroyed?.())return;Promise.resolve(win.webContents.executeJavaScript(source,false)).catch(e=>console.warn('[v0.17 shadow diagnostics] inject failed:',e?.message||String(e)))}catch(e){console.warn('[v0.17 shadow diagnostics] inject failed:',e?.message||String(e))}};try{win.webContents.on('did-finish-load',inject)}catch(e){console.warn('[v0.17 shadow diagnostics] hook failed:',e?.message||String(e))}})}
function pinStableUserData(){const stable=String(process.env.ARAM_UNIVERSAL_SHADOW_USER_DATA_ROOT||'').trim()||path.join(app.getPath('appData'),STABLE_APP_ID);const before=app.getPath('userData');if(path.resolve(before)!==path.resolve(stable))app.setPath('userData',stable);console.log('[v0.17.1 storage-root]',{before,stable,active:app.getPath('userData')});return stable}
function loadCanonicalRegistry(){const registry=require('./canonical/src/core/owner-registry.js');registry.assertSingleOwner?.();const rows=Object.values(registry.owners||{});if(registry.production_active!==true||rows.length!==15||!rows.every(x=>x?.status==='production'))throw new Error('v0.17 canonical owner registry inactive');return registry}
function installCanonicalRendererBridge(registry){const built=buildRendererSource({appDir:__dirname});app.on('browser-window-created',(_event,win)=>{const inject=()=>{try{if(!win||win.isDestroyed?.()||win.webContents?.isDestroyed?.())return;Promise.resolve(win.webContents.executeJavaScript(built.source,false)).then(result=>{if(!result?.production_active||Number(result?.owners_active)!==15)console.warn('[v0.17 canonical renderer bridge] owner layer did not report full activation')}).catch(e=>console.warn('[v0.17 canonical renderer bridge] inject failed:',e?.message||String(e)))}catch(e){console.warn('[v0.17 canonical renderer bridge] inject failed:',e?.message||String(e))}};try{win.webContents.on('did-finish-load',inject)}catch(e){console.warn('[v0.17 canonical renderer bridge] hook failed:',e?.message||String(e))}});return{production_active:true,owners_active:Object.keys(registry.owners||{}).length,modules:built.modules}}
function installV79SafetyBootstrap(){const updateSafety=require('./update-safety-v01579');let blackbox=null;try{blackbox=require('./freeze-blackbox-v01577')}catch{}const bootSafety=updateSafety.installBootGuard({version:VERSION,appDir:__dirname,record:blackbox?.record});if(bootSafety.rollbackScheduled)return{rollbackScheduled:true};if(!blackbox)blackbox=require('./freeze-blackbox-v01577');blackbox.install({version:VERSION});require('./hang-heartbeat-v01579').install({version:VERSION,record:blackbox.record});const {patchIndexText:patchInGame}=require('./ingame-transition-patch-v01575');const {patchIndexText:patchRenderAll}=require('./safe-index-patch-v01578');const indexPath=path.join(__dirname,'index.html');const before=fs.readFileSync(indexPath,'utf8');const a=patchInGame(before);if(!a.ok)throw new Error('v0.17 in-game index contract mismatch: '+JSON.stringify(a.results));const b=patchRenderAll(a.text);if(!b.ok)throw new Error('v0.17 renderAll index contract mismatch: '+JSON.stringify({status:b.status,count:b.count}));if(a.changed||b.changed){const backup=path.join(__dirname,'index.pre-v0170-stability.bak.html');if(!fs.existsSync(backup))fs.copyFileSync(indexPath,backup);fs.writeFileSync(indexPath,b.text,'utf8');blackbox.record('IDX-170','index-stability-patched',{inGame:!!a.changed,renderAll:!!b.changed})}const autosyncCore=require('./autosync-core');require('./autosync-live-runtime-v01571').patch(autosyncCore);return{rollbackScheduled:false}}
// Preserve v0.16.3 registration order: diagnostics -> Rating/storage -> canonical -> cold-start -> v79 safety -> legacy core.
installShadowDiagnostics();
const userData=pinStableUserData();
installUniversalRatingIpc({ipcMain,userDataPath:String(process.env.ARAM_UNIVERSAL_RATING_DB_ROOT||userData)});
const canonicalRegistry=loadCanonicalRegistry();
installCanonicalRendererBridge(canonicalRegistry);
try{require('./cold-start-promotion-v0160').install({appDir:__dirname,version:VERSION})}catch(e){try{console.warn('[v0.17 cold-start promotion] install failed:',e?.message||String(e))}catch{}}
const safety=installV79SafetyBootstrap();
if(safety.rollbackScheduled){module.exports={rollbackScheduled:true}}else{require('./legacy-runtime-v0170.js')}
