'use strict';
const IMPLEMENTATION_VERSION='0.16-shadow';
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0)),n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,avg=a=>a.length?a.reduce((x,y)=>x+n(y),0)/a.length:0,r1=v=>Math.round(n(v)*10)/10;
const G=v=>v>=96?'S+':v>=91?'S':v>=84?'A+':v>=76?'A':v>=64?'B':v>=52?'C':'D';
const AX=[['combat','전투 영향력'],['survival','생존 관리'],['resource','자원 효율'],['participation','교전 참여'],['role','역할 수행'],['consistency','안정성']];
function sort(rows){return rows.slice().sort((x,y)=>x.t&&y.t?y.t-x.t:0)}
function wa(a,k,L=20){a=a.slice(0,L);let s=0,d=0;a.forEach((x,i)=>{const w=a.length<2?1:1.22-i/(a.length-1)*.44;s+=n(x[k])*w;d+=w});return d?s/d:0}
function cons(a){const x=a.slice(0,20).map(z=>z.score);if(x.length<2)return 62;const m=avg(x),sd=Math.sqrt(avg(x.map(v=>(v-m)**2))),sw=x.length>=6?Math.abs(avg(x.slice(0,3))-avg(x.slice(-3))):0;return clamp(96-sd*2.35-sw*.35,35,96)}
function calc(rows){const a=rows.slice(0,20),r10=rows.slice(0,10),p10=rows.slice(10,20),c=cons(a),axes={combat:wa(a,'combat'),survival:wa(a,'survival'),resource:wa(a,'resource'),participation:wa(a,'participation'),role:wa(a,'score'),consistency:c},raw=axes.role*.5+axes.combat*.12+axes.survival*.1+axes.resource*.08+axes.participation*.08+c*.12,cf=Math.min(1,a.length/10),index=clamp(70+(raw-70)*(.45+.55*cf)),recent={},prev={};for(const[k]of AX){recent[k]=k==='consistency'?cons(r10):avg(r10.map(x=>x[k==='role'?'score':k]));prev[k]=p10.length>=5?(k==='consistency'?cons(p10):avg(p10.map(x=>x[k==='role'?'score':k]))):null}const roll=[];for(let i=0;i<=rows.length-5;i++)roll.push(avg(rows.slice(i,i+5).map(x=>x.score)));return{axes,index,form:avg(rows.slice(0,5).map(x=>x.score)),stability:c,trend:p10.length>=5?avg(r10.map(x=>x.score))-avg(p10.map(x=>x.score)):0,recent,prev,bestForm:roll.length?Math.max(...roll):avg(rows.map(x=>x.score)),best:rows.length?Math.max(...rows.map(x=>x.score)):0}}
function mastery(rows){const g={};rows.forEach(x=>(g[x.role]||(g[x.role]=[])).push(x));return Object.entries(g).map(([role,a])=>{const raw=avg(a.map(x=>x.score)),f=Math.min(1,a.length/5),score=clamp(70+(raw-70)*(.45+.55*f));return{role,n:a.length,score:r1(score),grade:G(score),tmp:a.length<5}}).sort((a,b)=>b.score-a.score)}
function decorate(input){const p={...input,rows:Array.isArray(input?.rows)?input.rows:[],axes:{...(input?.axes||{})}};const d={cc:avg(p.rows.slice(0,20).map(x=>x.cc)),eng:avg(p.rows.slice(0,20).map(x=>x.engage)),abs:avg(p.rows.slice(0,20).map(x=>x.absorb)),front:avg(p.rows.slice(0,20).map(x=>x.frontline)),peel:avg(p.rows.slice(0,20).map(x=>x.peel)),ally:avg(p.rows.slice(0,20).map(x=>x.ally)),dmg:avg(p.rows.slice(0,20).map(x=>x.damage)),poke:avg(p.rows.slice(0,20).map(x=>x.poke))},a=p.axes,t=[];(d.eng>=76||d.cc>=80)&&a.participation>=74&&t.push('🧠 교전 설계형');(d.abs>=78||d.front>=80)&&t.push('🛡️ 전열 선호');d.dmg>=82&&a.survival>=70&&t.push('🎯 후방 캐리형');(d.peel>=77||d.ally>=80)&&t.push('🤝 팀 보호형');a.resource>=82&&t.push('💰 고효율');a.combat>=80&&a.survival<60&&t.push('🔥 하이리스크 하이리턴');a.consistency>=82&&a.survival>=76&&t.push('🧊 안정 지향');d.poke>=82&&t.push('🏹 포킹 강점');a.participation>=85&&t.push('⚔️ 교전 적극적');p.tags=[...new Set(t.length?t:['⚖️ 밸런스형'])].slice(0,4);const s=AX.map(([k,l])=>({k,l,v:n(a[k])})).sort((x,y)=>y.v-x.v);p.strong=s.slice(0,2);p.weak=s.slice(-2).reverse();const tag=p.tags[0].replace(/^[^\s]+\s*/,'');p.scout=p.n<5?`10인 상세 표본 ${p.n}경기의 임시 프로필입니다. 최소 10경기 이상 누적될수록 평가가 안정됩니다.`:`${tag} 성향이 강합니다. ${p.strong[0].l}·${p.strong[1].l}이 현재 강점이고, 가장 큰 개선 여지는 ${p.weak[0].l}입니다. ${p.trend>=4?`최근 ROLE 흐름이 이전 구간보다 ${r1(p.trend)}점 상승했습니다.`:p.trend<=-4?`최근 ROLE 흐름이 이전 구간보다 ${Math.abs(r1(p.trend))}점 낮습니다.`:'최근 흐름은 장기 평균에서 크게 벗어나지 않습니다.'}`;p.fun=a.combat>=80&&a.survival<60?'“싸움은 잘 여는데, 퇴근도 조금 빠른 편.”':a.survival>=82&&a.combat>=80?'“죽지 않는 것도 딜이라는 걸 잘 아는 플레이어.”':a.resource>=84?'“많이 먹지 않아도 밥값을 하는 효율형.”':a.participation>=86?'“한타 출석률만큼은 개근에 가깝다.”':d.abs>=82?'“앞줄이 비면 일단 본인이 서고 보는 타입.”':'“한 장면보다 여러 경기에서 반복되는 습관으로 평가받는 타입.”';return p}
function buildProfile(rows,{total,mode='standard',modeLabel=mode==='mayhem'?'아수라장':'일반 칼바람',qid=mode==='mayhem'?2400:450}={}){rows=sort(rows||[]);const p={...calc(rows),rows,total:Number.isFinite(Number(total))?Number(total):rows.length,n:rows.length,roles:mastery(rows)},wins=rows.filter(x=>x.win).length;p.wins=wins;p.wr=rows.length?wins/rows.length:0;p.mode=mode;p.modeLabel=modeLabel;p.qid=qid;return decorate(p)}
module.exports={IMPLEMENTATION_VERSION,clamp,n,avg,r1,G,AX,sort,wa,cons,calc,mastery,decorate,buildProfile,production_active:false,score_logic_changed:false,profile_scoring_changed:false};
