'use strict';
const contract=require('./contract');
const results=require('./results-normalizer');
const metrics=require('./metrics');
const history=require('./history-service');
const riotGradeLink=require('./riot-grade-link');
const profileRender=require('./profile-render');
const resultsRender=require('./results-render');
const owner=require('./owner');
const universalRating=require('./universal-rating-adapter');
module.exports={contract,results,metrics,history,riotGradeLink,profileRender,resultsRender,owner,universalRating,production_active:false,score_logic_changed:false,random_scoring_changed:false,profile_scoring_changed:false,rating_production_active:false};
