'use strict';
const profileRender=require('./profile-render');
const resultsRender=require('./results-render');
const IMPLEMENTATION_VERSION='0.16-shadow';
const IDS=Object.freeze({style:'profileCanonicalStyleV016',launchWrap:'profileCanonicalLaunchV016',launch:'profileCanonicalOpenV016',overlay:'profileCanonicalOverlayV016',content:'profileCanonicalContentV016'});
const STYLE=`
[data-ui-role="profile-overlay"]{position:fixed;inset:0;z-index:470;background:#020813e8;display:none;align-items:center;justify-content:center;padding:16px}[data-ui-role="profile-overlay"].open{display:flex}.profileCanonicalModal{width:min(1120px,97vw);max-height:94vh;overflow:auto;background:#091625;border:1px solid #345772;border-radius:16px;color:#dcebf8}.pphead{position:sticky;top:0;z-index:3;background:#0b1929f5;border-bottom:1px solid #29415a;padding:13px 16px;display:flex;justify-content:space-between;align-items:center}.ppbody{padding:14px}.pphero{display:grid;grid-template-columns:.72fr 1.28fr;gap:10px}.ppbox{border:1px solid #29435d;background:#091727;border-radius:12px;padding:12px}.ppidx strong{display:block;font-size:48px}.ppidx i{font-style:normal;color:#9fe0ff;font-size:16px;font-weight:900}.ppstats,.ppaxes,.pproles{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin-top:10px}.ppstats div,.ppaxis,.pprole{border:1px solid #263e56;background:#081522;border-radius:8px;padding:7px}.ppradar{width:100%;height:255px}.pprg{fill:none;stroke:#274158}.pprs{stroke:#22394f}.pprc{fill:#27c3b638;stroke:#4cd9cf;stroke-width:2}.pprp{fill:#e8a23d18;stroke:#e0a24f;stroke-dasharray:5 4}.pprl{fill:#8ba8c0;font-size:9px;font-weight:800}.ppaxes{grid-template-columns:repeat(3,1fr)}.ppbar{height:4px;background:#13283a;border-radius:4px;margin-top:5px}.ppbar i{display:block;height:100%;background:#45bdc9}.ppgrid{display:grid;grid-template-columns:1.1fr .9fr;gap:10px;margin-top:10px}.pptags{display:flex;flex-wrap:wrap;gap:5px}.pptags span{border:1px solid #30526e;border-radius:99px;padding:4px 7px;font-size:8px;color:#afd6ed}.ppscout{font-size:10px;line-height:1.65;color:#bdd1e3;margin-top:9px}.ppfun{margin-top:8px;border-left:3px solid #3db8b0;padding:8px;background:#0a1f25;color:#9edbd5;font-size:9px}.ppsw{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.pproles{grid-template-columns:repeat(3,1fr)}.ppdev div{display:grid;grid-template-columns:1fr 45px 55px;border-bottom:1px solid #1c3044;padding:5px;font-size:8px}.up{color:#75d9b3}.down{color:#e59b9f}.ppempty{color:#748da4;font-size:9px}.ppfoot{margin-top:9px;color:#6f8ea8;font-size:8px;line-height:1.5}.ppx{border:1px solid #36516d;background:#14253a;color:#d9e8f6;border-radius:50%;width:34px;height:34px}.profileCanonicalOpen{border:1px solid #315f82;background:#102b42;color:#aee4ff;border-radius:9px;padding:8px 12px;font-size:9px;font-weight:900;cursor:pointer}.profileCanonicalOpen:disabled{opacity:.45}@media(max-width:850px){.pphero,.ppgrid{grid-template-columns:1fr}.ppaxes,.pproles{grid-template-columns:1fr 1fr}[data-ui-role="profile-overlay"]{align-items:flex-end;padding:0}.profileCanonicalModal{width:100%;max-height:96vh;border-radius:14px 14px 0 0}}`;
function createProfileOwner({document,getProfile=(()=>null),getResults=(()=>[]),normalizeGame=(x=>x),label=(()=> '조회 플레이어'),coach=(()=>null),champUrl=(()=>''),itemUrl=(()=>''),grade=(()=>'-'),onOpen=(()=>{}),onClose=(()=>{})}={}){
  if(!document)throw new Error('document required');let disposed=false,overlayListener=null,launchListener=null;
  function ensureStyle(){let st=document.getElementById?.(IDS.style);if(st)return st;st=document.createElement?.('style');if(!st)return null;st.id=IDS.style;st.textContent=STYLE;(document.head||document.body)?.appendChild?.(st);return st}
  function ensureOverlay(){let o=document.getElementById?.(IDS.overlay);if(o)return o;o=document.createElement?.('div');if(!o)return null;o.id=IDS.overlay;o.setAttribute?.('data-ui-role','profile-overlay');o.className='profileCanonicalOverlay';const modal=document.createElement?.('div'),content=document.createElement?.('div');if(!modal||!content)return null;modal.className='profileCanonicalModal';content.id=IDS.content;content.setAttribute?.('data-ui-role','profile-content');modal.appendChild?.(content);o.appendChild?.(modal);overlayListener=e=>{const close=e?.target===o||e?.target?.closest?.('[data-profile-action="close"]');if(close)closeProfile()};o.addEventListener?.('click',overlayListener);document.body?.appendChild?.(o);return o}
  function ensureLauncher(){let b=document.getElementById?.(IDS.launch);if(b)return b;const anchor=document.getElementById?.('historyQueueSwitch')||document.getElementById?.('historyListHint');if(!anchor)return null;const wrap=document.createElement?.('div'),btn=document.createElement?.('button');if(!wrap||!btn)return null;wrap.id=IDS.launchWrap;btn.id=IDS.launch;btn.className='profileCanonicalOpen';btn.type='button';btn.textContent='◈ PLAYER PROFILE · 종합 분석';btn.setAttribute?.('data-ui-role','profile-launch');launchListener=()=>openProfile();btn.addEventListener?.('click',launchListener);wrap.appendChild?.(btn);if(anchor.insertAdjacentElement)anchor.insertAdjacentElement('afterend',wrap);else anchor.parentElement?.appendChild?.(wrap);return btn}
  function renderProfile(p=getProfile()){if(disposed)return false;ensureStyle();ensureOverlay();ensureLauncher();const host=document.getElementById?.(IDS.content);if(!host)return false;host.innerHTML=profileRender.renderProfile(p,{label:label(),coachModel:coach(p)});const btn=document.getElementById?.(IDS.launch);if(btn)btn.disabled=!(p&&Number(p.n)>0);return true}
  function openProfile(){if(disposed)return false;renderProfile();const o=ensureOverlay();o?.classList?.add?.('open');onOpen();return !!o}
  function closeProfile(){const o=document.getElementById?.(IDS.overlay);o?.classList?.remove?.('open');onClose();return !!o}
  function renderResults(target,games=getResults()){if(disposed||!target)return false;const normalized=(Array.isArray(games)?games:[]).map(g=>normalizeGame(g));target.innerHTML=resultsRender.renderResults(normalized,{champUrl,itemUrl,grade});target.setAttribute?.('data-ui-role','results-host');return true}
  function renderAll({profile=getProfile(),resultsTarget=null,games=getResults()}={}){const a=renderProfile(profile),b=resultsTarget?renderResults(resultsTarget,games):true;return !!(a&&b)}
  function dispose(){if(disposed)return;disposed=true;const o=document.getElementById?.(IDS.overlay),b=document.getElementById?.(IDS.launch),w=document.getElementById?.(IDS.launchWrap),st=document.getElementById?.(IDS.style);if(o&&overlayListener)o.removeEventListener?.('click',overlayListener);if(b&&launchListener)b.removeEventListener?.('click',launchListener);o?.remove?.();w?.remove?.();st?.remove?.();overlayListener=null;launchListener=null}
  return{ensureStyle,ensureOverlay,ensureLauncher,renderProfile,openProfile,closeProfile,renderResults,renderAll,dispose,get disposed(){return disposed}};
}
module.exports={IMPLEMENTATION_VERSION,IDS,STYLE,createProfileOwner,production_active:false,score_logic_changed:false,profile_scoring_changed:false,owner_status:'shadow'};
