'use strict';
const metrics=require('./metrics');
const IMPLEMENTATION_VERSION='0.16-shadow';
const AX=metrics.AX;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const r1=metrics.r1;
const n=metrics.n;
const clamp=metrics.clamp;
function poly(vals,cx=180,cy=130,R=92){return vals.map((v,i)=>{const a=-Math.PI/2+i*Math.PI*2/vals.length,r=R*clamp(v)/100;return`${(cx+Math.cos(a)*r).toFixed(1)},${(cy+Math.sin(a)*r).toFixed(1)}`}).join(' ')}
function radar(p){const cx=180,cy=130,R=92,rings=[20,40,60,80,100].map(v=>`<polygon points="${poly(Array(6).fill(v),cx,cy,R)}" class="pprg"/>`).join(''),sp=AX.map((_,i)=>{const a=-Math.PI/2+i*Math.PI*2/6;return`<line x1="${cx}" y1="${cy}" x2="${cx+Math.cos(a)*R}" y2="${cy+Math.sin(a)*R}" class="pprs"/>`}).join(''),lab=AX.map(([k,l],i)=>{const a=-Math.PI/2+i*Math.PI*2/6,x=cx+Math.cos(a)*(R+27),y=cy+Math.sin(a)*(R+27),an=Math.cos(a)>.3?'start':Math.cos(a)<-.3?'end':'middle',v=Math.round(n(p?.recent?.[k]??p?.axes?.[k]));return`<text x="${x}" y="${y+3}" text-anchor="${an}" class="pprl">${esc(l)} <tspan>${v}</tspan></text>`}).join(''),pv=AX.map(([k])=>p?.prev?.[k]),old=pv.every(v=>v!=null)?`<polygon points="${poly(pv,cx,cy,R)}" class="pprp"/>`:'';return`<div data-ui-role="profile-radar"> <svg viewBox="0 0 360 270" class="ppradar">${rings}${sp}${old}<polygon points="${poly(AX.map(([k])=>p?.recent?.[k]??p?.axes?.[k]),cx,cy,R)}" class="pprc"/>${lab}</svg><div class="ppleg"><span>● 최근 10</span>${old?'<span>◇ 이전 10</span>':''}</div></div>`}
function strongWeak(p){const strong=Array.isArray(p?.strong)?p.strong:[],weak=Array.isArray(p?.weak)?p.weak:[];return`<div class="ppsw"><div><b>강점</b>${strong.map(x=>`<span>+ ${esc(x.l)} <b>${Math.round(n(x.v))}</b></span>`).join('')||'<span>-</span>'}</div><div><b>개선 여지</b>${weak.map(x=>`<span>− ${esc(x.l)} <b>${Math.round(n(x.v))}</b></span>`).join('')||'<span>-</span>'}</div></div>`}
function roles(p){const xs=Array.isArray(p?.roles)?p.roles:[];return xs.length?xs.map(x=>`<div class="pprole"><div><b>${esc(x.role)}</b><b>${esc(x.grade)}</b></div><strong>${Math.round(n(x.score))}</strong><small>${n(x.n)}경기${x.tmp?' · 임시평가':''}</small><div class="ppbar"><i style="width:${Math.round(clamp(x.score))}%"></i></div></div>`).join(''):'<div class="ppempty">표본 없음</div>'}
function development(p){if(p?.prev?.role==null)return'<div class="ppempty">비교용 이전 구간이 5경기 이상 쌓이면 표시됩니다.</div>';return AX.map(([k,l])=>({l,d:r1(n(p?.recent?.[k])-n(p?.prev?.[k])),v:Math.round(n(p?.recent?.[k]))})).sort((a,b)=>Math.abs(b.d)-Math.abs(a.d)).map(x=>`<div><span>${esc(x.l)}</span><b>${x.v}</b><em class="${x.d>1?'up':x.d<-1?'down':''}">${x.d>=0?'+':''}${x.d}</em></div>`).join('')}
function coach(p,model){if(model&&typeof model==='string')return model;const weak=Array.isArray(p?.weak)&&p.weak.length?p.weak[0]:null,title=model?.title||weak?.l||'다음 목표',text=model?.text||(`다음 경기에서는 ${weak?.l||'가장 낮은 축'}을 한 가지 행동 목표로 잡고 확인해보세요.`),status=model?.status||'';return`<div data-ui-role="profile-growth-coach"><div class="ppt"><b>GROWTH COACH</b>${status?`<em class="${esc(model?.ok===true?'ok':model?.ok===false?'no':'')}">${esc(status)}</em>`:''}</div><div class="ppscout"><b>${esc(title)}</b><br>${esc(text)}</div></div>`}
function renderProfile(p,{label='조회 플레이어',coachModel=null}={}){const name=esc(label);if(!p||!n(p.n)){return`<div data-ui-role="profile-content"><div class="pphead"><div><small>${name}</small><h2>PLAYER PROFILE</h2></div><button type="button" class="ppx" data-profile-action="close">×</button></div><div class="ppbody"><div class="ppempty">10인 상세 데이터가 없어 계산할 수 없습니다.</div></div></div>`}const confidence=p.n>=20?'높음':p.n>=10?'보통':p.n>=5?'낮음':'표본 부족',trend=p.trend>=2?'↑':p.trend<=-2?'↓':'→';return`<div data-ui-role="profile-content"><div class="pphead"><div><small>${name} · ${esc(p.modeLabel)} / Queue ${esc(p.qid)}</small><h2>PLAYER PROFILE · SCOUT REPORT</h2></div><button type="button" class="ppx" data-profile-action="close">×</button></div><div class="ppbody"><div class="pphero"><div class="ppbox ppidx" data-ui-role="profile-player-index"><small>PLAYER INDEX</small><strong>${r1(p.index)}</strong><i>${metrics.G(p.index)}</i><div class="ppstats"><div><span>최근 폼</span><b>${r1(p.form)} ${trend}</b></div><div><span>안정성</span><b>${Math.round(n(p.stability))}</b></div><div><span>최고 5경기 폼</span><b>${r1(p.bestForm)}</b></div><div><span>최고 단일 경기</span><b>${Math.round(n(p.best))}</b></div></div><small>분석 ${n(p.n)}/${n(p.total,p.n)}경기 · 신뢰도 ${confidence} · ${n(p.wins)}승 ${Math.max(0,n(p.n)-n(p.wins))}패</small></div><div class="ppbox">${radar(p)}</div></div><div class="ppaxes" data-ui-role="profile-axes">${AX.map(([k,l])=>`<div class="ppaxis"><div><span>${esc(l)}</span><b>${Math.round(n(p?.axes?.[k]))}</b></div><div class="ppbar"><i style="width:${Math.round(clamp(p?.axes?.[k]))}%"></i></div><small>${p?.prev?.[k]==null?'비교 표본 대기':`${r1(n(p?.recent?.[k])-n(p?.prev?.[k]))>=0?'+':''}${r1(n(p?.recent?.[k])-n(p?.prev?.[k]))}`}</small></div>`).join('')}</div><div class="ppgrid"><div class="ppbox" data-ui-role="profile-scout-report"><b>SCOUT REPORT</b><div class="pptags">${(p.tags||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="ppscout">${esc(p.scout||'')}</div><div class="ppfun">${esc(p.fun||'')}</div>${strongWeak(p)}</div><div class="ppbox" data-ui-role="profile-role-mastery"><b>ROLE MASTERY</b><div class="pproles">${roles(p)}</div></div></div><div class="ppgrid"><div class="ppbox" data-ui-role="profile-development"><b>DEVELOPMENT · 최근10 vs 이전10</b><div class="ppdev">${development(p)}</div></div><div class="ppbox">${coach(p,coachModel)}</div></div><div class="ppfoot">※ 앱 내부 지수이며 Riot 공식 랭크/전세계 백분위가 아닙니다. 10인 상세 전적만 사용하고 소표본을 보정합니다. 코멘트는 전적 수치 패턴만 설명하며 리플레이 장면·포지셔닝·스킬 사용을 직접 판독하지 않습니다.${p.mode==='mayhem'?' 아수라장은 증강 영향 포함 별도 프로필입니다.':''}</div></div></div>`}
module.exports={IMPLEMENTATION_VERSION,esc,poly,radar,strongWeak,roles,development,coach,renderProfile,production_active:false,score_logic_changed:false,profile_scoring_changed:false};
