'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.ARAMRatingResearchUICoreV01=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const MODEL_LABEL={elo:'기본 실력 점수',glicko:'신뢰도 반영 점수',trueskill_family:'종합 실력 추정'};
  const MODEL_SHORT={elo:'Elo',glicko:'Glicko',trueskill_family:'TrueSkill'};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=(v,d=null)=>Number.isFinite(Number(v))?Number(v):d,pct=v=>num(v)==null?'—':`${(Number(v)*100).toFixed(2)}%`,int=v=>num(v)==null?'—':Math.round(Number(v)).toLocaleString('en-US'),f=(v,d=3)=>num(v)==null?'—':Number(v).toFixed(d);
  const date=v=>{if(!v)return'—';const n=Number(v),d=new Date(Number.isFinite(n)?n:v);if(Number.isNaN(d.getTime()))return'—';return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const shortModel=k=>MODEL_SHORT[k]||String(k||'—'),labelModel=k=>MODEL_LABEL[k]||String(k||'—');
  const maskPuuid=p=>{const s=String(p||'');return s?`${s.slice(0,4)}…${s.slice(-4)}`:'(none)'};
  function normalizeRiotId(v){return String(v||'').normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase()}
  function riotIdOf(x){if(!x||typeof x!=='object')return'';const r=x.riotId||x.riotID||x.player?.riotId;if(r)return String(r);const g=x.gameName||x.player?.gameName,t=x.tagLine||x.tag||x.player?.tagLine;return g&&t?`${g}#${t}`:g?String(g):''}
  function puuidOf(x){return String(x?.puuid||x?.player?.puuid||'').trim()}
  function matchParticipants(g){for(const r of [g,g?.game,g?.match,g?.data,g?.raw,g?.info]){if(Array.isArray(r?.participants)&&r.participants.length)return r.participants;const a=Array.isArray(r?.team)?r.team:[],b=Array.isArray(r?.enemy)?r.enemy:[];if(a.length||b.length)return[...a,...b]}return[]}
  function modePuuidFromMatches(matches){const c=new Map();for(const m of Array.isArray(matches)?matches:[]){const p=puuidOf(m?.me);if(p)c.set(p,(c.get(p)||0)+1)}return[...c].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]||''}
  function resolveTargetIdentity(state,inputValue=''){
    const s=state||{},searched=s.targetMode==='searched',target=s.target||{},account=s.account||{},local=s.localAccount||{},matches=Array.isArray(s.matches)?s.matches:[];
    const searchRiotId=String(inputValue||riotIdOf(target)||riotIdOf(account)||'').trim();
    if(searched){
      const direct=puuidOf(target)||String(s.targetPuuid||'').trim()||puuidOf(account);if(direct)return{mode:'searched',search_riot_id:searchRiotId,puuid:direct,source:puuidOf(target)?'target.puuid':s.targetPuuid?'targetPuuid':'searched.account.puuid',reason:'resolved'};
      const wanted=new Set([searchRiotId,riotIdOf(target),riotIdOf(account)].map(normalizeRiotId).filter(Boolean));
      if(wanted.size)for(const m of matches)for(const p of matchParticipants(m)){if(wanted.has(normalizeRiotId(riotIdOf(p)))){const id=puuidOf(p);if(id)return{mode:'searched',search_riot_id:searchRiotId||riotIdOf(p),puuid:id,source:'searched.match.riot_id_to_puuid',reason:'resolved'}}}
      const me=modePuuidFromMatches(matches);if(me)return{mode:'searched',search_riot_id:searchRiotId,puuid:me,source:'searched.match.me_puuid',reason:'resolved'};
      return{mode:'searched',search_riot_id:searchRiotId,puuid:'',source:'none',reason:'resolved_puuid_missing'};
    }
    const current=puuidOf(local)||puuidOf(account)||String(s.puuid||'').trim()||modePuuidFromMatches(matches);return{mode:'current',search_riot_id:riotIdOf(local)||riotIdOf(account)||'',puuid:current,source:puuidOf(local)?'localAccount.puuid':puuidOf(account)?'current.account.puuid':s.puuid?'state.puuid':'current.match.me_puuid',reason:current?'resolved':'resolved_puuid_missing'};
  }
  function findPlayerId(run,puuid){if(!run||!puuid)return null;return run.identity?.puuid_to_player_id?.[String(puuid)]||null}
  function diagnosePlayer(run,resolution){const puuid=resolution?.puuid||'',pid=findPlayerId(run,puuid),player=pid?run?.players?.[pid]:null,models=player?.models||{},rating=!!(models.elo||models.glicko||models.trueskill_family);let reason='available';if(!puuid)reason='resolved_puuid_missing';else if(!pid)reason='puuid_not_in_research_identity';else if(!player)reason='player_state_missing';else if(!rating)reason='rating_state_missing';return{search_riot_id:resolution?.search_riot_id||'',resolved_puuid:puuid,masked_puuid:maskPuuid(puuid),player_id:pid,research_db_player_found:!!pid,observations:Number(player?.games)||0,rating_state_found:rating,reason}}
  function selectionText(sel,leader){const status=String(sel?.status||'unknown'),best=shortModel(sel?.best_observed||leader);if(status==='candidate_winner')return{status,title:'검증 상태',main:`현재 가장 잘 맞는 방식 · ${best}`,sub:'검증 기준을 통과한 연구 후보',tone:'candidate'};if(status==='no_clear_winner')return{status,title:'검증 상태',main:'최적 방식 검증 중',sub:`현재 가장 잘 맞는 방식: ${best} · 통계적 우위 미확인`,tone:'neutral'};if(status==='insufficient_real_data'||status==='insufficient_for_model_selection')return{status,title:'검증 상태',main:'검증 기준 통과 대기',sub:`현재 가장 잘 맞는 방식: ${best} · 데이터 추가 필요`,tone:'low'};return{status,title:'검증 상태',main:'평가 상태 확인 불가',sub:'분석 데이터 상태를 확인하세요.',tone:'low'}}
  function networkDensity(ds){const d=num(ds?.pair_graph_density,0),s=num(ds?.single_match_fraction,1);if(s>.75||d<.02)return{key:'LOW',label:'데이터 연결도 낮음'};if(s>.45||d<.08)return{key:'MEDIUM',label:'데이터 연결도 보통'};return{key:'HIGH',label:'데이터 연결도 높음'}}
  function uncertaintyLevel(p){const games=num(p?.games,0),g=num(p?.models?.glicko?.uncertainty,350),ts=num(p?.models?.trueskill_family?.raw?.sigma,25/3),e=num(p?.models?.elo?.uncertainty,350);if(games<=2||g>220||ts>7.2||e>220)return{key:'HIGH',label:'높음'};if(games<10||g>125||ts>5.2||e>110)return{key:'MEDIUM',label:'보통'};return{key:'LOW',label:'낮음'}}
  function scoreTrust(u){return u?.key==='HIGH'?'낮음':u?.key==='LOW'?'높음':'보통'}
  function dataConfidence(run,p){if(!run||!p)return{key:'NONE',label:'없음',reason:'분석 데이터에 플레이어 상태가 없습니다.'};const ds=run.dataset||{},games=num(p.games,0),leader=run.observed_leader||run.selection?.best_observed||'elo',cold=num(run.models?.[leader]?.frozen_cold_start?.player_fraction,1),single=num(ds.single_match_fraction,1),unc=uncertaintyLevel(p);if(games<=2)return{key:'LOW',label:'낮음',reason:'개인 관측이 1~2경기라 표본이 부족합니다.'};if(num(ds.matches,0)<250||cold>.5||single>.8)return{key:'LOW',label:'낮음',reason:'전체 분석 데이터가 아직 희소하고 신규 관측 비중이 높습니다.'};if(games<10||unc.key==='HIGH'||num(ds.matches,0)<500||cold>.25||single>.6)return{key:'MEDIUM',label:'보통',reason:'반복 관측은 형성됐지만 데이터가 아직 충분히 안정적이지 않습니다.'};if(games>=20&&unc.key==='LOW'&&num(ds.matches,0)>=500&&cold<=.15&&single<=.5)return{key:'HIGH',label:'높음',reason:'개인 반복 관측과 전체 데이터 품질이 모두 안정 구간입니다.'};return{key:'MEDIUM',label:'보통',reason:'개인 표본과 전체 데이터 품질을 함께 반영했습니다.'}}
  function sampleBadge(g){g=num(g,0);if(g<=2)return{key:'insufficient',label:'표본 부족'};if(g<10)return{key:'limited',label:'제한적 표본'};if(g<20)return{key:'repeat',label:'반복 관측'};return{key:'established',label:'반복 관측 20+'}}
  function trend(p){const q=p?.models?.glicko||p?.models?.elo||p?.models?.trueskill_family,h=Array.isArray(q?.history)?q.history:[];if(h.length<10)return{available:false,label:'추세 데이터 부족',points:[]};const rows=h.slice(-10),delta=num(rows.at(-1)?.rating,0)-num(rows[0]?.rating,0);return{available:true,label:`최근 10경기 ${delta>=0?'+':''}${Math.round(delta)}`,delta,points:rows.map(x=>num(x.rating,0))}}
  function sparkline(points){if(!Array.isArray(points)||points.length<2)return'';const lo=Math.min(...points),hi=Math.max(...points),span=Math.max(1e-9,hi-lo),w=116,h=28,p=points.map((v,i)=>`${(2+i*112/(points.length-1)).toFixed(1)},${(26-(v-lo)*24/span).toFixed(1)}`).join(' ');return`<svg class="arui-spark" viewBox="0 0 ${w} ${h}" aria-hidden="true"><polyline points="${p}" fill="none" stroke="currentColor" stroke-width="2"/></svg>`}
  function buildViewModel(run,puuid,opts={}){if(!run||run.schema!=='aram-rating-ui-latest-run-v01')return{kind:'unavailable',message:'Research data unavailable'};const dataset=run.dataset||{},pid=findPlayerId(run,puuid),selection=selectionText(run.selection,run.observed_leader),density=networkDensity(dataset),shared={run,dataset,selection,density,collection:{phase:dataset.phase||'UNKNOWN',status:dataset.collection_status||'unknown',sampling_version:dataset.sampling_version||'unknown',progress:`${int(dataset.matches)} / ${int(opts.hardCap||500)} matches`}};if(!pid||!run.players?.[pid])return{kind:'no_data',...shared,message:'이 플레이어는 아직 분석 데이터에 포함되지 않았습니다.'};const player=run.players[pid],uncertainty=uncertaintyLevel(player),models={};for(const key of['elo','glicko','trueskill_family']){const s=player.models?.[key];if(s)models[key]={key,label:labelModel(key),short:shortModel(key),rating:num(s.rating),uncertainty:num(s.uncertainty),games:num(s.games,player.games),raw:s.raw||null,validation:run.models?.[key]||null,is_primary:run.selection?.status==='candidate_winner'&&run.selection?.best_observed===key,is_observed_leader:run.observed_leader===key}}return{kind:'player',...shared,player_id:pid,player,models,confidence:dataConfidence(run,player),uncertainty,score_trust:scoreTrust(uncertainty),sample:sampleBadge(player.games),trend:trend(player),last_updated:date(player.last_match_at||dataset.latest_match_at),generated_at:date(run.generated_at)}}
  function modelCard(m,sample,trust){if(!m)return'';const muted=sample?.key==='insufficient'?' arui-model-muted':'',badge=m.is_primary?'<span class="arui-primary">검증 후보</span>':m.is_observed_leader?'<span class="arui-observed">현재 가장 잘 맞음</span>':'';let sub='';if(m.key==='elo')sub=`예상 범위 ±${int(m.uncertainty)} · Elo`;else if(m.key==='glicko')sub=`예상 오차 ±${int(m.uncertainty)} · Glicko`;else sub=`예상 오차 ±${int(m.uncertainty)} · 점수 신뢰도 ${trust} · TrueSkill`;return`<div class="arui-model${muted}${m.is_primary?' arui-model-primary':''}"><div class="arui-model-head"><span>${esc(m.label)}</span>${badge}</div><strong>${int(m.rating)}점</strong><small>${esc(sub)}</small></div>`}
  function metricRow(n,m){if(!m)return`<tr><td>${esc(n)}</td><td colspan="5">—</td></tr>`;return`<tr><td>${esc(n)}</td><td>${int(m.n)}</td><td>${f(m.log_loss,4)}</td><td>${f(m.brier,4)}</td><td>${f(m.ece,4)}</td><td>${m.accuracy==null?'—':pct(m.accuracy)}</td></tr>`}
  function details(vm){if(vm.kind!=='player')return'';const r=vm.run,b=r.baselines||{},ds=vm.dataset,ts=vm.models.trueskill_family,g=vm.models.glicko;return`<details class="arui-details"><summary>상세 분석 · 모델 비교</summary><div class="arui-detail-body"><div class="arui-detail-block"><h4>검증 지표 · Frozen</h4><table><thead><tr><th>방식</th><th>N</th><th>Log Loss</th><th>Brier</th><th>ECE</th><th>Accuracy</th></tr></thead><tbody>${metricRow('Elo',r.models?.elo?.frozen)}${metricRow('Glicko',r.models?.glicko?.frozen)}${metricRow('TrueSkill',r.models?.trueskill_family?.frozen)}${metricRow('50% 기준',b.constant_50?.frozen)}${metricRow('전체 승률 기준',b.historical_winrate?.frozen)}${metricRow('최근 승률 기준',b.recent_winrate?.frozen)}</tbody></table></div><div class="arui-detail-grid"><div class="arui-detail-block"><h4>모델 상태</h4><dl><div><dt>검증 상태</dt><dd>${esc(selectionText(r.selection,r.observed_leader).main)}</dd></div><div><dt>현재 가장 잘 맞는 방식</dt><dd>${esc(shortModel(r.observed_leader))}</dd></div><div><dt>Frozen 신규 관측</dt><dd>${pct(r.models?.[r.observed_leader]?.frozen_cold_start?.player_fraction)}</dd></div><div><dt>Walk-forward 신규 관측</dt><dd>${pct(r.models?.[r.observed_leader]?.walk_forward_cold_start?.player_fraction)}</dd></div></dl></div><div class="arui-detail-block"><h4>원본 점수 정보</h4><dl><div><dt>추정 실력 (μ)</dt><dd>${ts?.raw?.mu==null?'—':f(ts.raw.mu,2)}</dd></div><div><dt>점수 불확실성 (σ)</dt><dd>${ts?.raw?.sigma==null?'—':f(ts.raw.sigma,2)}</dd></div><div><dt>예상 오차 (RD)</dt><dd>${g?.uncertainty==null?'—':`±${int(g.uncertainty)}`}</dd></div></dl></div></div><div class="arui-detail-block"><h4>분석 데이터</h4><dl><div><dt>경기 / 플레이어</dt><dd>${int(ds.matches)} / ${int(ds.players)}</dd></div><div><dt>1경기만 관측</dt><dd>${pct(ds.single_match_fraction)}</dd></div><div><dt>2+ / 5+ / 10+</dt><dd>${int(ds.players_2_plus)} / ${int(ds.players_5_plus)} / ${int(ds.players_10_plus)}</dd></div><div><dt>${esc(vm.density.label)}</dt><dd>${pct(ds.largest_component_fraction)}</dd></div></dl></div><div class="arui-disclaimer">개인 연구용 비공식 지표입니다. Riot 공식 MMR·랭크가 아니며 최종 방식은 검증 기준 통과 전 확정하지 않습니다.</div></div></details>`}
  function shell(head,body){return`<section id="aramRatingResearchCardV01" class="arui-card${body.includes('arui-empty')?' arui-state':''}"><div class="arui-head"><div><span class="arui-badge" title="개인 연구용 비공식 지표입니다. Riot 공식 MMR 또는 랭크가 아닙니다.">RESEARCH</span><h3>ARAM 실력 분석</h3>${head?`<small>${esc(head)}</small>`:''}</div><button class="arui-refresh" data-arui-action="refresh" title="로컬 분석 데이터 새로 계산">↻</button></div>${body}</section>`}
  function renderCard(vm){const ds=vm.dataset||{};if(vm.kind==='unavailable')return shell('',`<div class="arui-empty">Research data unavailable<small>연구 데이터 로드에 실패했습니다. 기존 전적검색에는 영향을 주지 않습니다.</small></div>`);if(vm.kind==='no_data')return shell('',`<div class="arui-empty"><b>분석 데이터 없음</b><small>${esc(vm.message)}</small></div><div class="arui-dataset-mini"><span>분석 데이터 ${int(ds.matches)}경기</span><span>${int(ds.players)}명</span><span>2+ ${int(ds.players_2_plus)}</span></div>`);const p=vm.player,t=vm.trend;return shell('세 가지 계산 방식을 함께 비교하는 개인 연구 화면',`<div class="arui-summary"><div><small>분석 데이터</small><b>${int(ds.matches)}경기</b></div><div class="arui-confidence ${esc(vm.confidence.key.toLowerCase())}"><small>데이터 신뢰도</small><b>${esc(vm.confidence.label)}</b><em>${esc(vm.confidence.reason)}</em></div><div><small>2경기 이상 관측 비율</small><b>${pct(1-num(ds.single_match_fraction,1))}</b><em>2+ 관측 ${int(ds.players_2_plus)}명</em></div></div><div class="arui-research-status ${esc(vm.selection.tone)}"><div><small>${esc(vm.selection.title)}</small><b>${esc(vm.selection.main)}</b></div><span>${esc(vm.selection.sub)}</span></div><div class="arui-models">${modelCard(vm.models.elo,vm.sample,vm.score_trust)}${modelCard(vm.models.glicko,vm.sample,vm.score_trust)}${modelCard(vm.models.trueskill_family,vm.sample,vm.score_trust)}</div><div class="arui-player-meta"><div><small>관측 경기</small><b>${int(p.games)}경기</b><span class="arui-sample ${esc(vm.sample.key)}">${esc(vm.sample.label)}</span></div><div><small>최근 업데이트</small><b>${esc(vm.last_updated)}</b></div><div><small>점수 신뢰도</small><b>${esc(vm.score_trust)}</b></div><div class="arui-trend"><small>최근 변화</small><b>${esc(t.label)}</b>${t.available?sparkline(t.points):''}</div></div><div class="arui-dataset-mini"><span>분석 데이터 ${int(ds.matches)} / ${int(ds.players)}</span><span>1경기만 관측 ${pct(ds.single_match_fraction)}</span><span>2+ ${int(ds.players_2_plus)}</span><span>5+ ${int(ds.players_5_plus)}</span><span>10+ ${int(ds.players_10_plus)}</span><span>${esc(vm.density.label)}</span></div>${details(vm)}<div class="arui-foot">Riot 공식 MMR/랭크가 아닙니다 · ${esc(vm.collection.phase)} ${esc(String(vm.collection.status).toUpperCase())} · Sampling ${esc(vm.collection.sampling_version)}</div>`)}
  return{MODEL_LABEL,MODEL_SHORT,selectionText,networkDensity,uncertaintyLevel,scoreTrust,dataConfidence,sampleBadge,trend,findPlayerId,resolveTargetIdentity,diagnosePlayer,maskPuuid,buildViewModel,renderCard,details};
});
