'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const exists=p=>fs.existsSync(path.join(ROOT,p));
const report={generatedAt:new Date().toISOString(),pass:[],fail:[],info:{}};
const ok=(cond,name,detail='')=>(cond?report.pass:report.fail).push({name,detail});
const ge=(a,b)=>{const A=String(a||'0').split('.').map(Number),B=String(b||'0').split('.').map(Number),n=Math.max(A.length,B.length);for(let i=0;i<n;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return true};
const m=JSON.parse(read('update/manifest.json'));
const byPath=new Map((m.files||[]).map(x=>[x.path,x.source]));
const patchPath=byPath.get('item-art-hotfix-v01563.js');
const mainPath=byPath.get('main.js'),pkgPath=byPath.get('package.json');
ok(ge(m.version,'0.15.63'),'Manifest version is v0.15.63 or newer',m.version);
ok(!!patchPath&&/v0\.15\.63\/item-art-hotfix-v01563\.js$/.test(patchPath)&&exists(patchPath),'v0.15.63 item-art hotfix remains delivered',patchPath||'missing');
ok(!!mainPath&&exists(mainPath),'Current main delivered',mainPath||'missing');
ok(!!pkgPath&&exists(pkgPath),'Current package delivered',pkgPath||'missing');
const patch=patchPath&&exists(patchPath)?read(patchPath):'',main=mainPath&&exists(mainPath)?read(mainPath):'',pkg=pkgPath&&exists(pkgPath)?JSON.parse(read(pkgPath)):{};
for(const [code,name] of [[patch,'item-art hotfix'],[main,'current main']]){try{new Function(code);ok(true,`${name} parses as JavaScript`)}catch(e){ok(false,`${name} parses as JavaScript`,e.message)}}
ok(/__ARAM_ITEM_ART_HOTFIX_V01563__\s*=\s*true/.test(patch),'v0.15.63 readiness marker exists');
ok(/'3143'/.test(patch)&&/3143_randuins_omen\.png/.test(patch)&&/란두인의 예언/.test(patch),'Randuin current base-art override is explicit');
ok(/'3075'/.test(patch)&&/3075_thornmail\.png/.test(patch)&&/가시 갑옷/.test(patch),'Thornmail current base-art override is explicit');
ok(/latest\/game\/assets\/items\/icons2d/.test(patch),'Hotfix uses latest game current-base-art path');
ok(/aramArtV01560/.test(patch),'Hotfix prevents v0.15.60 refresh from restoring stale catalog art');
ok(/score_logic_changed:false/.test(patch),'Item-art hotfix is score-neutral');
const poolPos=main.indexOf("'random-party-pool-labels-v01562.js'");
const artPos=main.indexOf("'item-art-hotfix-v01563.js'");
const rolePos=main.indexOf("'role-metric-detail-v01518.js'");
ok(poolPos>=0&&artPos>poolPos&&rolePos>artPos,'Current main preserves v0.15.63 item-art hotfix before role detail');
ok(main.includes('__ARAM_ITEM_ART_HOTFIX_V01563__'),'Current main readiness guard covers v0.15.63');
const vm=(main.match(/const VERSION='([^']+)'/)||[])[1]||'';
ok(ge(vm,'0.15.63'),'Current main VERSION is v0.15.63 or newer',vm);
ok(ge(pkg.version,'0.15.63'),'Package version is v0.15.63 or newer',pkg.version);
report.info={scope:'Historical priority-1 Randuin/Thornmail correction remains regression-covered while v0.15.64+ may supersede it with a global resolver.',scoreLogicChanged:false,remoteArtSource:'CommunityDragon latest game/assets/items/icons2d',ids:['3143','3075'],forwardCompatible:true};
report.summary={pass:report.pass.length,fail:report.fail.length,status:report.fail.length?'FAIL':'PASS'};
fs.mkdirSync(path.join(ROOT,'audit-output'),{recursive:true});
fs.writeFileSync(path.join(ROOT,'audit-output','v01563-report.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(report.summary));for(const x of report.fail)console.error('FAIL',x.name,x.detail||'');process.exitCode=report.fail.length?1:0;
