'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const exists=p=>fs.existsSync(path.join(ROOT,p));
const report={generatedAt:new Date().toISOString(),pass:[],fail:[],info:{}};
const ok=(cond,name,detail='')=>(cond?report.pass:report.fail).push({name,detail});
const ge=(a,b)=>{const A=String(a||'0').split('.').map(Number),B=String(b||'0').split('.').map(Number),n=Math.max(A.length,B.length);for(let i=0;i<n;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return true};
const m=JSON.parse(read('update/manifest.json'));
const byPath=new Map((m.files||[]).map(x=>[x.path,x.source]));
const fixPath=byPath.get('random-party-label-fix-v01561.js');
const mainPath=byPath.get('main.js'),pkgPath=byPath.get('package.json');
ok(ge(m.version,'0.15.61'),'Manifest is v0.15.61 or newer',m.version);
ok(!!fixPath&&/v0\.15\.61\/random-party-label-fix-v01561\.js$/.test(fixPath)&&exists(fixPath),'v0.15.61 party label fix runtime delivered',fixPath||'missing');
ok(!!mainPath&&exists(mainPath),'Current main delivered',mainPath||'missing');
ok(!!pkgPath&&exists(pkgPath),'Current package delivered',pkgPath||'missing');
const fix=fixPath&&exists(fixPath)?read(fixPath):'',main=mainPath&&exists(mainPath)?read(mainPath):'',pkg=pkgPath&&exists(pkgPath)?JSON.parse(read(pkgPath)):{};
for(const [code,name] of [[fix,'v0.15.61 party label fix'],[main,'main']]){try{new Function(code);ok(true,`${name} parses as JavaScript`)}catch(e){ok(false,`${name} parses as JavaScript`,e.message)}}
ok(/__ARAM_RANDOM_PARTY_LABEL_FIX_V01561__\s*=\s*true/.test(fix),'v0.15.61 readiness marker exists');
ok(/rpPartySyncedV01558/.test(fix)&&/rpManualLockedV01558/.test(fix)&&/randomState\?\.manual/.test(fix),'Fix derives visibility from actual v0.15.58/manual row state, not an existing v0.15.59 pill');
ok(/document\.createElement\('span'\)/.test(fix)&&/rpPartyLabelV01561/.test(fix)&&/textContent='팀원픽'/.test(fix),'Fix directly creates a visible 팀원픽 pill when row state is active');
ok(/우리 파티 챔피언 · 고정할 픽만 선택/.test(fix),'Manual-party section copy is simplified');
ok(/rpPartyStatePillV01559\{display:none!important\}/.test(fix),'Legacy v0.15.59 pill is hidden to prevent duplicate labels');
ok(/internal_manual_lock_state_preserved:true/.test(fix)&&/score_logic_changed:false/.test(fix),'Visible copy changes preserve manual-lock semantics and recommendation scoring');
const v60=main.indexOf("'ui-refresh-v01560.js'"),v61=main.indexOf("'random-party-label-fix-v01561.js'"),role=main.indexOf("'role-metric-detail-v01518.js'");
ok(v60>=0&&v61>v60&&role>v61,'Main injects v0.15.61 after v0.15.60 and before role detail');
ok(main.includes('__ARAM_RANDOM_PARTY_LABEL_FIX_V01561__'),'Main readiness guard covers v0.15.61');
const vm=(main.match(/const VERSION='([^']+)'/)||[])[1]||'';
ok(ge(vm,'0.15.61'),'Current main VERSION is v0.15.61 or newer',vm);
ok(ge(pkg.version,'0.15.61'),'Current package VERSION is v0.15.61 or newer',pkg.version);
report.info={scope:'Real-Windows follow-up: always show 팀원픽 for active manual or AutoSync party rows and simplify section title.',scoreLogicChanged:false,internalManualLockPreserved:true,exactSelectors:['#random','#manualPartyInputs']};
report.summary={pass:report.pass.length,fail:report.fail.length,status:report.fail.length?'FAIL':'PASS'};
fs.mkdirSync(path.join(ROOT,'audit-output'),{recursive:true});
fs.writeFileSync(path.join(ROOT,'audit-output','v01561-report.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(report.summary));for(const x of report.fail)console.error('FAIL',x.name,x.detail||'');process.exitCode=report.fail.length?1:0;
