'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const exists=p=>fs.existsSync(path.join(ROOT,p));
const report={generatedAt:new Date().toISOString(),pass:[],fail:[],info:{}};
const ok=(cond,name,detail='')=>(cond?report.pass:report.fail).push({name,detail});
const ge=(a,b)=>{const A=String(a||'0').split('.').map(Number),B=String(b||'0').split('.').map(Number),n=Math.max(A.length,B.length);for(let i=0;i<n;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return true};
const m=JSON.parse(read('update/manifest.json'));
const byPath=new Map((m.files||[]).map(x=>[x.path,x.source]));
const uiPath=byPath.get('ui-refresh-v01560.js'),catalogPath=byPath.get('item-catalog-v01527.js'),mainPath=byPath.get('main.js'),pkgPath=byPath.get('package.json');
ok(ge(m.version,'0.15.60'),'Manifest is v0.15.60 or newer',m.version);
ok(!!uiPath&&/v0\.15\.60\/ui-refresh-v01560\.js$/.test(uiPath)&&exists(uiPath),'v0.15.60 UI refresh runtime delivered',uiPath||'missing');
ok(!!catalogPath&&/v0\.15\.(?:60|6[4-9]|[7-9]\d)\/item-catalog-v01527\.js$/.test(catalogPath)&&exists(catalogPath),'Stable item-catalog filename remains delivered, allowing newer art catalog revisions',catalogPath||'missing');
ok(!!mainPath&&exists(mainPath),'Current main delivered',mainPath||'missing');
ok(!!pkgPath&&exists(pkgPath),'Current package delivered',pkgPath||'missing');
const ui=uiPath&&exists(uiPath)?read(uiPath):'',catalog=catalogPath&&exists(catalogPath)?read(catalogPath):'',main=mainPath&&exists(mainPath)?read(mainPath):'',pkg=pkgPath&&exists(pkgPath)?JSON.parse(read(pkgPath)):{};
for(const [code,name] of [[ui,'v0.15.60 UI refresh'],[catalog,'current item catalog'],[main,'main']]){try{new Function(code);ok(true,`${name} parses as JavaScript`)}catch(e){ok(false,`${name} parses as JavaScript`,e.message)}}
ok(/__ARAM_UI_REFRESH_V01560__\s*=\s*true/.test(ui),'v0.15.60 readiness marker exists');
ok(/visible_party_label:'팀원픽'/.test(ui)&&/internal_manual_lock_state_preserved:true/.test(ui),'Visible party labels are unified while internal lock state is preserved');
ok(/rpPartyStatePillV01559\.manual::after/.test(ui)&&/content:'팀원픽'/.test(ui),'Manual state visibly renders as 팀원픽 without rewriting recommendation state');
ok(/score_logic_changed:false/.test(ui),'v0.15.60 UI refresh is score-neutral');
ok(/raw\.communitydragon\.org\/latest/.test(catalog)&&/v1\/items\.json/.test(catalog)&&/iconPath/.test(catalog),'Catalog reads latest Riot-client item icon metadata from CommunityDragon mirror');
ok(/ddragon\.leagueoflegends\.com/.test(catalog)&&/Data Dragon/.test(catalog),'Data Dragon icon fallback is retained');
ok(/recipeAware:true/.test(catalog)&&/map12/.test(catalog)&&/from/.test(catalog)&&/into/.test(catalog),'Existing ARAM recipe-aware item metadata is preserved');
ok(/img\.riItemIconV01556/.test(ui)&&/img\.aramItemIconV01557/.test(ui)&&/#historyMatchDetail \.matchItems img/.test(ui),'v0.15.60 refresh still covers its historical item-image surfaces');
ok(/dataset\.aramArtFallbackV01560/.test(ui)&&/style\.display='none'/.test(ui),'v0.15.60 image failure handling remains present');
const oldAt=main.indexOf("'random-item-icons-v01556.js'"),globalAt=main.indexOf("'item-icons-global-v01557.js'"),refreshAt=main.indexOf("'ui-refresh-v01560.js'"),roleAt=main.indexOf("'role-metric-detail-v01518.js'");
ok(oldAt>=0&&globalAt>oldAt&&refreshAt>globalAt&&roleAt>refreshAt,'Main preserves v0.15.60 after existing item visual layers');
const v58At=main.indexOf("'random-party-picks-v01558.js'"),v59At=main.indexOf("'random-party-labels-v01559.js'"),coachAt=main.indexOf("'random-ingame-coach-v01550.js'");
ok(v58At>=0&&v59At>v58At&&coachAt>v59At,'v0.15.59 historical ordering remains intact between v0.15.58 and in-game coach',`${v58At}/${v59At}/${coachAt}`);
const perfAt=main.indexOf("'runtime-performance-v01567.js'");
if(ge(m.version,'0.15.67'))ok(perfAt>v58At&&perfAt<v59At,'v0.15.67 may insert a compatibility/performance owner before historical v0.15.59 initialization',`${v58At}/${perfAt}/${v59At}`);
ok(main.includes('__ARAM_UI_REFRESH_V01560__'),'Main readiness guard covers v0.15.60');
const vm=(main.match(/const VERSION='([^']+)'/)||[])[1]||'';
ok(ge(vm,'0.15.60'),'Current main VERSION is v0.15.60 or newer',vm);
ok(ge(pkg.version,'0.15.60'),'Current package VERSION is v0.15.60 or newer',pkg.version);
report.info={scope:'Historical v0.15.60 party-label and item-art layer remains regression-covered while later versions may replace/preempt historical visual runtimes with compatibility owners and newer unified artwork resolvers.',scoreLogicChanged:false,forwardCompatible:true};
report.summary={pass:report.pass.length,fail:report.fail.length,status:report.fail.length?'FAIL':'PASS'};
fs.mkdirSync(path.join(ROOT,'audit-output'),{recursive:true});
fs.writeFileSync(path.join(ROOT,'audit-output','v01560-report.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(report.summary));for(const x of report.fail)console.error('FAIL',x.name,x.detail||'');process.exitCode=report.fail.length?1:0;
