'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const exists=p=>fs.existsSync(path.join(ROOT,p));
const report={generatedAt:new Date().toISOString(),pass:[],fail:[],info:{}};
const ok=(cond,name,detail='')=>(cond?report.pass:report.fail).push({name,detail});
const ge=(a,b)=>{const A=String(a||'0').split('.').map(Number),B=String(b||'0').split('.').map(Number),n=Math.max(A.length,B.length);for(let i=0;i<n;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return true};
const m=JSON.parse(read('update/manifest.json'));
const byPath=new Map((m.files||[]).map(x=>[x.path,x.source]));
const patchPath=byPath.get('random-party-pool-labels-v01562.js');
const mainPath=byPath.get('main.js'),pkgPath=byPath.get('package.json');
ok(ge(m.version,'0.15.62'),'Manifest is v0.15.62 or newer',m.version);
ok(!!patchPath&&/v0\.15\.62\/random-party-pool-labels-v01562\.js$/.test(patchPath)&&exists(patchPath),'v0.15.62 pool-label runtime delivered',patchPath||'missing');
ok(!!mainPath&&exists(mainPath),'Current main delivered',mainPath||'missing');
ok(!!pkgPath&&exists(pkgPath),'Current package delivered',pkgPath||'missing');
const s=patchPath&&exists(patchPath)?read(patchPath):'',main=mainPath&&exists(mainPath)?read(mainPath):'',pkg=pkgPath&&exists(pkgPath)?JSON.parse(read(pkgPath)):{};
for(const [code,name] of [[s,'v0.15.62 pool labels'],[main,'main']]){try{new Function(code);ok(true,`${name} parses as JavaScript`)}catch(e){ok(false,`${name} parses as JavaScript`,e.message)}}
ok(/__ARAM_RANDOM_PARTY_POOL_LABELS_V01562__\s*=\s*true/.test(s),'v0.15.62 readiness marker exists');
ok(/#manualPartyInputs/.test(s)&&/#poolInputs/.test(s),'Patch uses exact Random Practice party/pool IDs');
ok(/randomState\?\.manual/.test(s)&&/rpPartySyncedV01558/.test(s),'Team-pick set includes manual locks and AutoSync-displayed party picks');
ok(/randomPoolTeamBadgeV01562/.test(s)&&/textContent='팀원픽'/.test(s)&&/slot\.appendChild\(badge\)/.test(s),'팀원픽 badge is created in the remaining-random pool slot');
ok(/randomPoolTakenBadge/.test(s)&&/external_pick_precedence:true/.test(s),'Existing external-pick badge keeps precedence');
ok(/rpPartyLabelV01561/.test(s)&&/display:none!important/.test(s)&&/left_inline_team_label_hidden:true/.test(s),'Left manual-party inline 팀원픽 pill is hidden');
ok(/score_logic_changed:false/.test(s),'Patch is explicitly score-neutral');
const v61=main.indexOf("'random-party-label-fix-v01561.js'"),v62=main.indexOf("'random-party-pool-labels-v01562.js'"),role=main.indexOf("'role-metric-detail-v01518.js'");
ok(v61>=0&&v62>v61&&role>v62,'Main injects v0.15.62 after v0.15.61 and before role detail');
ok(main.includes('__ARAM_RANDOM_PARTY_POOL_LABELS_V01562__'),'Main readiness guard covers v0.15.62');
const vm=(main.match(/const VERSION='([^']+)'/)||[])[1]||'';
ok(ge(vm,'0.15.62'),'Current main VERSION is v0.15.62 or newer',vm);
ok(ge(pkg.version,'0.15.62'),'Current package VERSION is v0.15.62 or newer',pkg.version);
report.info={scope:'Real-Windows correction: show 팀원픽 in remaining-random candidate slot, not inside manual-party input.',scoreLogicChanged:false,externalPickPrecedence:true,exactSelectors:['#manualPartyInputs','#poolInputs']};
report.summary={pass:report.pass.length,fail:report.fail.length,status:report.fail.length?'FAIL':'PASS'};
fs.mkdirSync(path.join(ROOT,'audit-output'),{recursive:true});
fs.writeFileSync(path.join(ROOT,'audit-output','v01562-report.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(report.summary));for(const x of report.fail)console.error('FAIL',x.name,x.detail||'');process.exitCode=report.fail.length?1:0;
