'use strict';
const IMPLEMENTATION_VERSION='0.16-shadow';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s??'').replace(/\s+/g,' ').trim();
const short=(s,n=92)=>{s=norm(s);return s.length>n?s.slice(0,n-1)+'…':s};
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function stateMeta(m){if(m.life==='dead')return{icon:'☠️',title:`사망 분석 · 부활 ${m.respawn||0}초`,tag:'ANALYZE'};if(m.life==='respawn')return{icon:'⚡',title:`부활 준비 · ${m.respawn||0}초`,tag:'READY'};if(m.life==='alive')return{icon:'⚔️',title:'전투 모드',tag:'LIVE'};return{icon:'⌛',title:'인게임 연결 대기',tag:'WAIT'}}
function autoTabFor(life){return life==='dead'?'build':'live'}
function renderLive(m){
  if(m.life==='waiting')return `<div class="riWaiting"><div><b>인게임 연결 대기</b><span>일반 칼바람 게임에 들어가면 자동으로 전투 모드가 시작됩니다.<br>지금 디자인을 확인하려면 상단 <b>인게임 미리보기</b>를 누르세요.</span></div></div>`;
  const plan=m.plan||{},tone=plan.tone||'warn',state=m.life==='dead'?'사망 중 판단':m.life==='respawn'?'부활 직전':'NOW CALL',time=`${String(Math.floor(num(m.gameTime)/60)).padStart(2,'0')}:${String(Math.floor(num(m.gameTime)%60)).padStart(2,'0')}`,threatSub=m.threat?.dead?`사망 · ${m.threat.respawn||0}초`:`${m.threat?.damageType||'-'} · ${m.threat?.score?Math.round(m.threat.score)+'점':'-'}`;
  return `<div class="riHero ${esc(tone)}"><div class="riHeroTop"><span>${esc(state)}</span><em>${esc(m.source==='preview'?'가상 경기':`LIVE ${time}`)} · 생존 ${m.alive.our}:${m.alive.enemy}</em></div><h3>${esc(plan.headline||'현재 교전 판단')}</h3><p>${esc(short(plan.detail||'',120))}</p></div><div class="riMetrics"><div class="riMetric"><span>최고 위협</span><b>${esc(m.threat?.name||'-')}</b><small>${esc(threatSub)}</small></div><div class="riMetric"><span>내 역할</span><b>${esc(m.job||'-')}</b><small>행동 한 줄만 표시</small></div><div class="riMetric"><span>다음 구매</span><b>${esc(m.item?.name||'-')}</b><small>${esc(m.buildSame?'통계 기본트리와 일치':'이번 판 상황 보정')}</small></div><div class="riMetric"><span>현재 구도</span><b>${esc(m.matchup||'-')}</b><small>우리 ${m.alive.our} : ${m.alive.enemy} 상대</small></div></div>${m.warning?`<div class="riAlert ${esc(m.warning.tone||'warn')}"><span>${m.warning.tone==='good'?'✓':'!'}</span><b>${esc(short(m.warning.text,118))}</b></div>`:''}`;
}
function renderBuild(m){
  if(m.life==='waiting')return renderLive(m);
  const source=m.stat?.source||'앱 기본 DB',basic=m.stat?.tree||'통계 기본트리 정보 없음',same=m.buildSame,alts=(m.alts||[]).filter(Boolean),respawn=m.life==='dead'?`<div class="riRespawnStrip"><strong>${m.respawn||0}초</strong><span>부활까지 · 지금은 구매/분석 확인 시간</span><b>보유 골드 ${Math.round(num(m.gold)).toLocaleString('ko-KR')}</b></div>`:`<div class="riRespawnStrip"><strong>${m.life==='respawn'?`${m.respawn||0}초`:'LIVE'}</strong><span>${m.life==='respawn'?'곧 부활 · 구매보다 다음 한타 준비':'현재 생존 · 필요할 때만 빌드 확인'}</span><b>보유 골드 ${Math.round(num(m.gold)).toLocaleString('ko-KR')}</b></div>`;
  return `${respawn}<div class="riBuildCompare"><div class="riBuildCard"><div class="riBuildCardHead"><span>통계 기본트리</span><i>${esc(m.stat?.verified?`검증 ${m.stat.verified}`:'BASE')}</i></div><div class="riBuildTree">${esc(basic)}</div><div class="riBuildSub">${esc(source)}</div></div><div class="riBuildCard opt"><div class="riBuildCardHead"><span>이번 판 최적화</span><i class="${same?'same':''}">${same?'기본과 일치':'상황 대응'}</i></div><div class="riBuildMain">${esc(m.item?.name||'-')}</div><div class="riBuildSub">${esc(short(m.item?.reason||m.advice?.direction||'',100))}</div>${alts.length?`<div class="riAltRow">${alts.map(x=>`<span class="riAltChip">대안 · ${esc(x)}</span>`).join('')}</div>`:''}</div></div><div class="riOneLine"><b>다음 한타:</b> ${esc(m.job||'-')}${m.threat?.name&&m.threat.name!=='-'?` · <b>${esc(m.threat.name)}</b> 대응 우선`:''}</div>`;
}
function detailThreats(m){const xs=(m.threats||[]).slice(0,5);if(!xs.length)return'<div class="riOneLine">상대 위협 데이터 대기</div>';return `<div class="riThreatRows">${xs.map((x,i)=>{const dead=!!x.isDead||!!x.dead||num(x.respawnTimer)>0||num(x.respawn)>0;return `<div class="riThreatRow"><i>${i+1}</i><b>${esc(x.name||'-')}</b><span>${esc(x.damageType||'-')}</span><em>${dead?`사망 ${Math.ceil(num(x.respawnTimer||x.respawn))}초`:Math.round(num(x.score))+'점'}</em></div>`}).join('')}</div>`}
function renderDetail(m){if(m.life==='waiting')return renderLive(m);const p=m.power||{},steps=(m.plan?.steps||[]).slice(0,4);return `<div class="riDetails"><details><summary>상대 위협 TOP5</summary><div class="riDetailBody">${detailThreats(m)}</div></details><details><summary>한타 상세</summary><div class="riDetailBody"><div class="riOneLine"><b>${esc(m.plan?.headline||'현재 판단')}</b><br>${esc(short(m.plan?.detail||'',140))}</div>${steps.length?`<div class="riOneLine">${steps.map((x,i)=>`<b>${i+1}.</b> ${esc(short(x,90))}`).join('<br>')}</div>`:''}</div></details><details><summary>파워 · 부활 상세</summary><div class="riDetailBody"><div class="riDetailGrid"><div class="riDetailCard"><span>LIVE 파워</span><b>${Math.round(num(p.our))} : ${Math.round(num(p.enemy))}</b></div><div class="riDetailCard"><span>평균 레벨</span><b>${num(p.ourLevelAvg).toFixed(1)} : ${num(p.enemyLevelAvg).toFixed(1)}</b></div><div class="riDetailCard"><span>평균 아이템 가치</span><b>${Math.round(num(p.ourItemAvg)).toLocaleString('ko-KR')} : ${Math.round(num(p.enemyItemAvg)).toLocaleString('ko-KR')}</b></div></div><div class="riOneLine"><b>생존:</b> 우리 ${m.alive.our} : ${m.alive.enemy} 상대 · <b>내 상태:</b> ${m.life==='dead'?`사망 ${m.respawn}초`:m.life==='respawn'?`곧 부활 ${m.respawn}초`:'생존'}</div></div></details></div>`}
function renderBody(tab,m){return tab==='build'?renderBuild(m):tab==='detail'?renderDetail(m):renderLive(m)}
function renderSignature({preview={active:false,state:'alive',scenario:'even',role:'tank'},ui={tab:'live',auto:true},model:m}={}){m=m||{};return JSON.stringify([!!preview.active,preview.state,preview.scenario,preview.role,ui.tab,!!ui.auto,m.source,m.life,Math.floor(num(m.gameTime)/2),m.respawn,m.alive?.our,m.alive?.enemy,m.threat?.name,Math.round(num(m.threat?.score)),m.item?.name,m.matchup,m.warning?.text])}
function nextUiState(ui,model,{force=false,preview={active:false,state:'alive',scenario:'even',role:'tank'}}={}){const next={tab:ui?.tab||'live',auto:ui?.auto!==false,lastLife:ui?.lastLife||'',lastRenderSig:ui?.lastRenderSig||''};if(next.auto&&model?.life!==next.lastLife){next.tab=autoTabFor(model?.life);next.lastLife=model?.life||''}else if(!next.auto&&model?.life!==next.lastLife)next.lastLife=model?.life||'';const sig=renderSignature({preview,ui:next,model});const shouldRender=!!force||sig!==next.lastRenderSig;if(shouldRender)next.lastRenderSig=sig;return{ui:next,signature:sig,shouldRender,body:shouldRender?renderBody(next.tab,model):null,meta:stateMeta(model||{})}}
module.exports={IMPLEMENTATION_VERSION,esc,norm,short,num,stateMeta,autoTabFor,renderLive,renderBuild,detailThreats,renderDetail,renderBody,renderSignature,nextUiState,production_active:false,score_logic_changed:false,random_scoring_changed:false};
